=== ahimanikya/FrescoMDM/solutions/aus-patient/AUSPatient/src/MatchEngine/schema/comparatorsList.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema attributeFormDefault="unqualified" elementFormDefault="qualified" version="1.0" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="comparators-list" type="comparators-listType" />
  <xsd:complexType name="comparators-listType">
    <xsd:sequence>
      <xsd:element name="group" type="groupType" minOccurs="1" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="groupType">
    <xsd:sequence>
      <xsd:element name="comparator" type="comparatorType" minOccurs="1" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="description" type="xsd:string" />
    <xsd:attribute name="path" type="xsd:string" />
  </xsd:complexType>
  <xsd:complexType name="comparatorType">
    <xsd:sequence>
      <xsd:element name="className" type="xsd:string" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="codes" type="codesType" minOccurs="1"/>
      <xsd:element name="params" type="paramsType" minOccurs="0"/>
      <xsd:element name="data-sources" type="data-sourcesType" minOccurs="0"/>
      <xsd:element name="dependency-classes" type="dependClasses" minOccurs="0"/>
      <xsd:element name="curve-adjust" type="curveAdjust" minOccurs="0"/>
    </xsd:sequence>
    <xsd:attribute name="description" type="xsd:string" />
  </xsd:complexType>
  <xsd:complexType name="data-sourcesType">
    <xsd:sequence>
      <xsd:element name="data-source" type="data-sourceType" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="data-sourceType">
    <xsd:attribute name="description" type="xsd:string" />
    <xsd:attribute name="name" type="xsd:string" />
    <xsd:attribute name="type" type="xsd:string" />
  </xsd:complexType>
  <xsd:complexType name="paramsType">
    <xsd:sequence>
      <xsd:element minOccurs="0" maxOccurs="unbounded" name="param" type="paramType" />
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="codesType">
    <xsd:sequence>
      <xsd:element minOccurs="1" maxOccurs="unbounded" name="code" type="codeType" />
    </xsd:sequence>
  </xsd:complexType>  
  <xsd:complexType name="dependClasses">
    <xsd:sequence>
      <xsd:element minOccurs="0" maxOccurs="unbounded" name="dependency-class" type="classType" />
    </xsd:sequence>
  </xsd:complexType>  
  <xsd:complexType name="curveAdjust">
    <xsd:attribute name="status"/>
  </xsd:complexType>    
  <xsd:complexType name="paramType">
    <xsd:attribute name="description" type="xsd:string" />
    <xsd:attribute name="name" type="xsd:string" />
    <xsd:attribute name="type" type="xsd:string" />
  </xsd:complexType>
  <xsd:complexType name="codeType">
    <xsd:attribute name="description" type="xsd:string" />
    <xsd:attribute name="name" type="xsd:string" />
  </xsd:complexType>  
  <xsd:complexType name="classType">
    <xsd:attribute name="matchfield" type="xsd:string"/>
    <xsd:attribute name="name" type="xsd:string"/>
  </xsd:complexType> 
</xsd:schema>

=== ahimanikya/FrescoMDM/index-core/src/main/resources/matchengine/config/runtime/match/comparatorsList.xml
<?xml version="1.0" encoding="UTF-8"?>
<comparators-list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="comparatorsList.xsd">
    <group description="Original group of comparators" path="com.sun.mdm.matcher.comparators.base">
        <comparator description="Simple Bigram Comparator">
            <className>BigramComparator</className>
            <codes>
                <code description="Bigram comparator" name="b1" />
            </codes>
            <params/>           
            <data-sources/>
        </comparator>
        <comparator description="Advanced Bigram Comparator">
            <className>AdvancedBigramComparator</className>
            <codes>
                <code description="Advanced Bigram comparator" name="b2" />
            </codes>
            <params/>          
            <data-sources/>
        </comparator>  
        <comparator description="Condensed String comparator">
            <className>CondensedStringComparator</className>
            <codes>            
                <code description="Condensed String comparator" name="us"/>
            </codes>   
            <params/>                            
            <data-sources/>
        </comparator>              
        <comparator description="Condensed AlphaNumeric comparator">
            <className>CondensedSSNComparator</className>
            <codes>            
               <code description="Condensed AlphaNumeric SSN comparator" name="nS" />
            </codes>   
             <params>
                <param description="Fixed length option" name="ssnLength" type="java.lang.Integer"/>
                <param description="record type" name="recType" type="java.lang.String"/>   
                <param description="List of SSN patterns" name="ssnList" type="java.lang.Character"/>                   
            </params>                                    
            <data-sources/>
        </comparator>              
        <comparator description="Date comparator">
            <className>DateComparator</className>
            <codes>
               <code description="Date comparator with days as units"  name="d" /> 
               <code description="Date comparator with days as units"  name="dD" /> 
               <code description="Date comparator with months as units" name="dM" /> 
               <code description="Date comparator with years as units" name="dY" /> 
               <code description="Date comparator with hours as units" name="dH" /> 
               <code description="Date comparator with minutes as units" name="dm" /> 
               <code description="Date comparator with seconds as units" name="ds"/> 
            </codes>
            <params>
               <param description="Methods choice option" name="switch" type="java.lang.String"/>
               <param description="lower limit" name="lLimit" type="java.lang.Integer"/>   
               <param description="upper limit" name="uLimit" type="java.lang.Integer"/>                   
            </params>               
            <data-sources/>
            <dependency-classes>
               <dependency-class description="The first dep-class" name="com.sun.mdm.matcher.comparators.base.JaroAdvancedSSNComparator"/>
            </dependency-classes>
        </comparator>   
        <comparator description="Advanced Jaro string comparator">
            <className>JaroAdvancedStringComparator</className>
            <codes>            
               <code description="Advanced Jaro String Comparator" name="u" />
               <code description="Advanced Jaro Adjusted for first names" name="uf" />
               <code description="Advanced Jaro Adjusted for last names" name="ul" />
               <code description="Advanced Jaro numbers" name="un" />
            </codes>   
            <params/>                            
            <data-sources/>
        </comparator>       
        <comparator description="Advanced Jaro SSN comparator">
            <className>JaroAdvancedSSNComparator</className>
            <codes>            
               <code description="Advanced Jaro AlphaNumeric Comparator" name="uan" />
            </codes>   
             <params>
                <param description="Fixed length option" name="ssnLength" type="java.lang.Integer"/>
                <param description="record type" name="recType" type="java.lang.String"/>   
                <param description="List of SSN patterns" name="ssnList" type="java.lang.Character"/>                   
            </params>                                  
            <data-sources/>
        </comparator>   
        <comparator description="Numerics comparator">
            <className>NumericsComparator</className>
            <codes>            
               <code description="Real numbers comparator" name="n[R, ]"/>
               <code description="Integers comparator" name="nI" />
            </codes>   
             <params>
               <param description="distance/string comparison option" name="switch" type="java.lang.String"/>
               <param description="Spectrum of comparison" name="range" type="java.lang.Integer"/>              
            </params>                                  
            <data-sources/>
        </comparator>            
        <comparator description="Unicode SSN comparator">
            <className>UnicodeSSNComparator</className>
            <codes>            
               <code description="The unicode AlphaNumeric Comparator" name="usus" />
            </codes>   
             <params>
                <param description="Fixed length option" name="ssnLength" type="java.lang.Integer"/>
                <param description="record type" name="recType" type="java.lang.String"/>   
                <param description="List of SSN patterns" name="ssnList" type="java.lang.Character"/>                   
            </params>                                  
            <data-sources/>
        </comparator>  
        <comparator description="Unicode string comparator">
            <className>UnicodeStringComparator</className>
            <codes>            
               <code description="Unicode String Comparator" name="usu" />
            </codes>   
             <params>
                <param description="Language used" name="language" type="java.lang.String"/>       
            </params>                                      
            <data-sources/>
        </comparator>    
        <comparator description="Winkler-Jaro string comparator">
            <className>WinklerJaroStringComparator</className>
            <codes>            
               <code description="Winkler-Jaro string comparator" name="ua" />
            </codes>   
            <params/>                            
            <data-sources/>
        </comparator> 
        <comparator description="Exact comparator">
            <className>ExactComparator</className>
            <codes>            
               <code description="Exact character-to-character comparator" name="c" />
            </codes>   
            <params/>                            
            <data-sources/>
        </comparator>  
        <comparator description="Prorated comparator">
            <className>ProratedComparator</className>
            <codes>            
               <code description="Prorated comparator" name="p" />
            </codes>   
            <params>
                <param description="The range" name="range" type="java.lang.Integer"/>
                <param description="First tolerance" name="tolerance1" type="java.lang.Integer"/>   
                <param description="Second tolerance" name="tolerance2" type="java.lang.Integer"/>                   
            </params>                         
            <data-sources/>
        </comparator>                 
    </group>
    <group description="Group of test comparators" path="com.sun.mdm.matcher.comparators.addon">
        <comparator description="A test comparator">
            <className>NewStringComparator</className>
            <codes>                
                <code description="The x1" name="x1" />
                <code description="The x2" name="x2" />
                <code description="The x3" name="x3" />
            </codes>    
            <params>
                <param description="Param 1" name="param1" type="java.lang.Integer"/>
                <param description="Param 2" name="param2" type="java.lang.Integer"/>   
                <param description="Param 3" name="param3" type="java.lang.Integer"/>                   
            </params>              
            <data-sources/>                  
        </comparator>
    </group>
</comparators-list>

=== ahimanikya/FrescoMDM/solutions/aus-patient/AUSPatient/src/MatchEngine/comparatorsList.xml
<?xml version="1.0" encoding="UTF-8"?>
<comparators-list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema/comparatorsList.xsd">
    <group description="Original group of comparators" path="com.sun.mdm.matcher.comparators.base">
        <comparator description="Simple Bigram Comparator">
            <className>BigramComparator</className>
            <codes>
                <code description="Bigram Comparator" name="b1" />
            </codes>
        </comparator>
        <comparator description="Advanced Bigram Comparator">
            <className>AdvancedBigramComparator</className>
            <codes>
                <code description="Advanced Bigram Comparator" name="b2" />
            </codes>
        </comparator>  
        <comparator description="Condensed String comparator">
            <className>CondensedStringComparator</className>
            <codes>            
                <code description="Condensed String Comparator" name="us"/>
            </codes>   
        </comparator>              
        <comparator description="Condensed AlphaNumeric comparator">
            <className>CondensedSSNComparator</className>
            <codes>            
               <code description="Condensed AlphaNumeric SSN Comparator" name="nS" />
            </codes>   
             <params>
                <param description="Fixed length option" name="ssnLength" type="java.lang.Integer"/>
                <param description="record type(Numeric(nu)/Alpha-Numeric(an))" name="recType" type="java.lang.String"/>   
                <param description="List of SSN excluded character patterns" name="ssnList" type="java.lang.Character[]"/>                   
            </params>                                    
            <data-sources/>
        </comparator>              
        <comparator description="Date comparator">
            <className>DateComparator</className>
            <codes>
               <code description="Date Comparator With Days as Units"  name="d[D, ]" /> 
               <code description="Date Comparator With Months as Units" name="dM" /> 
               <code description="Date Comparator With Years as Units" name="dY" /> 
               <code description="Date Comparator With Hours as Units" name="dH" /> 
               <code description="Date Comparator With Minutes as Units" name="dm" /> 
               <code description="Date Comparator With Seconds as Units" name="ds"/> 
            </codes>
            <params>
               <param description="Methods choice option" name="switch" type="java.lang.String"/>
               <param description="lower limit" name="lLimit" type="java.lang.Integer"/>   
               <param description="upper limit" name="uLimit" type="java.lang.Integer"/>                   
            </params>               
            <data-sources/>
            <dependency-classes>
               <dependency-class matchfield="String" name="com.sun.mdm.matcher.comparators.base.JaroAdvancedSSNComparator"/>
            </dependency-classes>
        </comparator>   
        <comparator description="Advanced Jaro string comparator">
            <className>JaroAdvancedStringComparator</className>
            <codes>            
               <code description="Advanced Jaro String Comparator" name="u" />
               <code description="Advanced Jaro Adjusted for First Names" name="uf" />
               <code description="Advanced Jaro Adjusted for Last Names" name="ul" />
               <code description="Advanced Jaro Adjusted for House Numbers" name="un" />
            </codes>   
            <params/>                            
            <data-sources/>
            <dependency-classes/>
            <curve-adjust status="true"/>
        </comparator>       
        <comparator description="Advanced Jaro SSN comparator">
            <className>JaroAdvancedSSNComparator</className>
            <codes>            
               <code description="Advanced Jaro AlphaNumeric Comparator" name="ujs" />
            </codes>   
             <params>
                <param description="Fixed length option" name="ssnLength" type="java.lang.Integer"/>
                <param description="record type" name="recType" type="java.lang.String"/>   
                <param description="List of SSN excluded character patterns" name="ssnList" type="java.lang.Character[]"/>                   
            </params>                                  
            <data-sources/>
            <dependency-classes/>
        </comparator>   
        <comparator description="Numerics comparator">
            <className>NumericsComparator</className>
            <codes>            
               <code description="Real Number Comparator" name="n[R, ]"/>
               <code description="Integer Comparator" name="nI" />
            </codes>   
             <params>
               <param description="distance/string comparison option" name="switch" type="java.lang.String"/>
               <param description="Spectrum of comparison" name="range" type="java.lang.Integer|java.lang.Double"/>              
            </params>                                  
            <data-sources/>
            <dependency-classes>
                <dependency-class matchfield="CSC" name="com.sun.mdm.matcher.comparators.base.CondensedStringComparator"/>               
            </dependency-classes>
            <curve-adjust status="false"/>
        </comparator>            
        <comparator description="Unicode SSN comparator">
            <className>UnicodeSSNComparator</className>
            <codes>            
               <code description="Unicode AlphaNumeric Comparator" name="usus" />
            </codes>   
             <params>
                <param description="Language used" name="language" type="java.lang.String"/>    
                <param description="Fixed length option" name="ssnLength" type="java.lang.Integer"/>
                <param description="record type" name="recType" type="java.lang.String"/>   
                <param description="List of SSN excluded character patterns" name="ssnList" type="java.lang.Character[]"/>                   
            </params>                                  
            <data-sources/>
        </comparator>  
        <comparator description="Unicode string comparator">
            <className>UnicodeStringComparator</className>
            <codes>            
               <code description="Unicode String Comparator" name="usu" />
            </codes>   
             <params>
                <param description="Language used" name="language" type="java.lang.String"/>       
            </params>                                      
            <data-sources/>
        </comparator>    
        <comparator description="Winkler-Jaro string comparator">
            <className>WinklerJaroStringComparator</className>
            <codes>            
               <code description="Winkler-Jaro String Comparator" name="ua" />
            </codes>   
            <params/>                            
            <data-sources/>
            <curve-adjust status="true"/>
        </comparator> 
        <comparator description="Exact comparator">
            <className>ExactComparator</className>
            <codes>            
               <code description="Exact Character-to-Character Comparator" name="c" />
            </codes>   
            <params/>                            
            <data-sources/>
        </comparator>  
        <comparator description="Prorated comparator">
            <className>ProratedComparator</className>
            <codes>            
               <code description="Prorated Comparator" name="p" />
            </codes>   
            <params>
                <param description="The range" name="range" type="java.lang.Integer"/>
                <param description="First tolerance" name="tolerance1" type="java.lang.Integer"/>   
                <param description="Second tolerance" name="tolerance2" type="java.lang.Integer"/>                   
            </params>                         
            <data-sources/>
        </comparator>                 
    </group>
</comparators-list>
