=== ahimanikya/FrescoMDM/index-core/src/main/resources/schema/db-domain.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
 # DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 #
 # Copyright 2003-2007 Sun Microsystems, Inc. All Rights Reserved.
 #
 # The contents of this file are subject to the terms of the Common 
 # Development and Distribution License ("CDDL")(the "License"). You 
 # may not use this file except in compliance with the License.
 #
 # You can obtain a copy of the License at
 # https://open-dm-mi.dev.java.net/cddl.html
 # or open-dm-mi/bootstrap/legal/license.txt. See the License for the 
 # specific language governing permissions and limitations under the  
 # License.  
 #
 # When distributing the Covered Code, include this CDDL Header Notice 
 # in each file and include the License file at
 # open-dm-mi/bootstrap/legal/license.txt.
 # If applicable, add the following below this CDDL Header, with the 
 # fields enclosed by brackets [] replaced by your own identifying 
 # information: "Portions Copyrighted [year] [name of copyright owner]"
-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="DatabaseDomainDefinition">
		<xs:annotation>
			<xs:documentation>Database Domain Definitions</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="domains">
					<xs:complexType>
						<xs:sequence maxOccurs="unbounded">
							<xs:element name="domain">
								<xs:complexType>
									<xs:attribute name="domain-type" type="xs:string" use="required"/>
									<xs:attribute name="sql-type" type="DatatypeOracle" use="required"/>
									<xs:attribute name="java-type" type="JavaType" use="required"/>
									<xs:attribute name="length" type="xs:positiveInteger" use="optional"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="db-type" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="oracle"/>
									<xs:enumeration value="sybase"/>
									<xs:enumeration value="sqlserver"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="DatatypeOracle">
		<xs:annotation>
			<xs:documentation>Oracle Data Types</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="varchar2"/>
			<xs:enumeration value="date"/>
			<xs:enumeration value="time"/>
			<xs:enumeration value="number"/>
			<xs:enumeration value="long"/>
			<xs:enumeration value="char"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="JavaType">
		<xs:annotation>
			<xs:documentation>Java Types</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="String"/>
			<xs:enumeration value="Date"/>
			<xs:enumeration value="Integer"/>
			<xs:enumeration value="BigDecimal"/>
			<xs:enumeration value="Boolean"/>
			<xs:enumeration value="Time"/>
			<xs:enumeration value="Timestamp"/>
			<xs:enumeration value="Long"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== ahimanikya/FrescoMDM/index-core/src/main/resources/schema/db-domain.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 # DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 #
 # Copyright 2003-2007 Sun Microsystems, Inc. All Rights Reserved.
 #
 # The contents of this file are subject to the terms of the Common 
 # Development and Distribution License ("CDDL")(the "License"). You 
 # may not use this file except in compliance with the License.
 #
 # You can obtain a copy of the License at
 # https://open-dm-mi.dev.java.net/cddl.html
 # or open-dm-mi/bootstrap/legal/license.txt. See the License for the 
 # specific language governing permissions and limitations under the  
 # License.  
 #
 # When distributing the Covered Code, include this CDDL Header Notice 
 # in each file and include the License file at
 # open-dm-mi/bootstrap/legal/license.txt.
 # If applicable, add the following below this CDDL Header, with the 
 # fields enclosed by brackets [] replaced by your own identifying 
 # information: "Portions Copyrighted [year] [name of copyright owner]"
-->

<DatabaseDomainDefinition xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="db-domain.xsd">
	<domains db-type="oracle">
		<domain domain-type="domain-name" sql-type="varchar2" java-type="String" length="40"/>
		<domain domain-type="domain-sequence" sql-type="number" java-type="BigDecimal" length="15"/>
		<domain domain-type="domain-date" sql-type="date" java-type="Date"/>
		<domain domain-type="domain-coded" sql-type="varchar2" java-type="String" length="8"/>
		<domain domain-type="domain-id" sql-type="varchar2" java-type="String" length="15"/>
		<domain domain-type="domain-system" sql-type="varchar2" java-type="String" length="20"/>
		<domain domain-type="domain-id-long" sql-type="varchar2" java-type="String" length="25"/>
		<domain domain-type="domain-boolean" sql-type="char" java-type="String" length="1"/>
		<domain domain-type="domain-description" sql-type="varchar2" java-type="String" length="50"/>
		<domain domain-type="domain-user-id" sql-type="varchar2" java-type="String" length="20"/>
		<domain domain-type="domain-timestamp" sql-type="date" java-type="Date"/>
		<domain domain-type="domain-soundex" sql-type="varchar2" java-type="String" length="8"/>
		<domain domain-type="domain-string-short" sql-type="varchar2" java-type="String" length="10"/>
		<domain domain-type="domain-string" sql-type="varchar2" java-type="String" length="20"/>
		<domain domain-type="domain-string-long" sql-type="varchar2" java-type="String" length="40"/>
		<domain domain-type="domain-nysiis" sql-type="varchar2" java-type="String" length="8"/>
		<domain domain-type="domain-binary" sql-type="long" java-type="String" length="900000"/>
		<domain domain-type="domain-number" sql-type="number" java-type="Long" length="15"/>
		<domain domain-type="domain-name-long" sql-type="varchar2" java-type="String" length="100"/>
	</domains>
</DatabaseDomainDefinition>
