=== ahimanikya/FrescoMDM/index-core/src/main/resources/schema/object.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
 # DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 #
 # Copyright 2003-2007 Sun Microsystems, Inc. All Rights Reserved.
 #
 # The contents of this file are subject to the terms of the Common 
 # Development and Distribution License ("CDDL")(the "License"). You 
 # may not use this file except in compliance with the License.
 #
 # You can obtain a copy of the License at
 # https://open-dm-mi.dev.java.net/cddl.html
 # or open-dm-mi/bootstrap/legal/license.txt. See the License for the 
 # specific language governing permissions and limitations under the  
 # License.  
 #
 # When distributing the Covered Code, include this CDDL Header Notice 
 # in each file and include the License file at
 # open-dm-mi/bootstrap/legal/license.txt.
 # If applicable, add the following below this CDDL Header, with the 
 # fields enclosed by brackets [] replaced by your own identifying 
 # information: "Portions Copyrighted [year] [name of copyright owner]"
-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="children">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="code-module">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="constraint-by" type="xs:string"/>
	<xs:element name="database" type="xs:string"/>
	<xs:element name="dateformat" type="xs:string"/>
	<xs:element name="Configuration">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name"/>
				<xs:element ref="database"/>
				<xs:element ref="dateformat"/>
				<xs:element ref="nodes" maxOccurs="unbounded"/>
				<xs:element ref="relationships" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="hierarchy" minOccurs="0" maxOccurs="1"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="field-name">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="field-type">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
        <xs:element name="fields">
            <xs:complexType>
                <xs:all>
                    <xs:element ref="field-name"/>
                    <xs:element ref="field-type"/>
                    <xs:element ref="size" minOccurs="0"/>
                    <xs:element ref="updateable"/>
                    <xs:element ref="required"/>
                    <xs:element ref="code-module" minOccurs="0"/>
                    <xs:element ref="pattern" minOccurs="0"/>
                    <xs:element ref="key-type"/>
                    <xs:element ref="user-code" minOccurs="0"/>
                    <xs:element ref="constraint-by" minOccurs="0"/>
                    <xs:element ref="minimum-value" minOccurs="0"/>
                    <xs:element ref="visible" minOccurs="0"/>
                </xs:all>
            </xs:complexType>
        </xs:element>
	<xs:element name="key-type" type="xs:boolean"/>
	<xs:element name="minimum-value" type="xs:date"/>
	<xs:element name="name" type="xs:string"/>
	<xs:element name="nodes">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="tag"/>
				<xs:element ref="fields" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="pattern">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<!-- multi-level object data model -->
	<xs:element name="node">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="name" type="xs:string" />
            <xs:element ref="node" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
  </xs:element>
  <!-- multi-level object data model -->
	<xs:element name="hierarchy">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="node" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
	</xs:element>
	<xs:element name="relationships">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="children" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="required" type="xs:boolean"/>
	<xs:element name="size">
		<xs:simpleType>
			<xs:restriction base="xs:short"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="tag">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="updateable" type="xs:boolean"/>
	<xs:element name="user-code" type="xs:string"/>
	<xs:element name="visible" type="xs:boolean"/>
</xs:schema>

=== ahimanikya/FrescoMDM/solutions/aus-patient/AUSPatient/src/Configuration/object.xml
<?xml version="1.0" encoding="UTF-8"?>
<Configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema/object.xsd">
    <name>AUSPatient</name>
    <database>Oracle</database>
    <dateformat>MM/dd/yyyy</dateformat>
    <nodes>
        <tag>AUSPatient</tag>
        <fields>
            <field-name>FirstName</field-name>
            <field-type>string</field-type>
            <size>40</size>
            <updateable>true</updateable>
            <required>true</required>
            <code-module></code-module>
            <pattern></pattern>
            <key-type>false</key-type>
        </fields>
        <fields>
            <field-name>FirstName_Std</field-name>
            <field-type>string</field-type>
            <size>40</size>
            <updateable>true</updateable>
            <required>false</required>
            <code-module></code-module>
            <pattern></pattern>
            <key-type>false</key-type>
        </fields>
        <fields>
            <field-name>FirstName_Phon</field-name>
            <field-type>string</field-type>
            <size>8</size>
            <updateable>true</updateable>
            <required>false</required>
            <code-module></code-module>
            <pattern></pattern>
            <key-type>false</key-type>
        </fields>
        <fields>
            <field-name>MiddleName</field-name>
            <field-type>string</field-type>
            <size>30</size>
            <updateable>true</updateable>
            <required>false</required>
            <code-module></code-module>
            <pattern></pattern>
            <key-type>false</key-type>
        </fields>
        <fields>
            <field-name>MiddleName_Std</field-name>
            <field-type>string</field-type>
            <size>40</size>
            <updateable>true</updateable>
            <required>false</required>
            <code-module></code-module>
            <pattern></pattern>
            <key-type>false</key-type>
        </fields>
        <fields>
            <field-name>MiddleName_Phon</field-name>
            <field-type>string</field-type>
            <size>8</size>
            <updateable>true</updateable>
            <required>false</required>
            <code-module></code-module>
            <pattern></pattern>
            <key-type>false</key-type>
        </fields>
        <fields>
            <field-name>LastName</field-name>
            <field-type>string</field-type>
            <size>40</size>
            <updateable>true</updateable>
            <required>true</required>
            <code-module></code-module>
            <pattern></pattern>
            <key-type>false</key-type>
        </fields>
        <fields>
            <field-name>LastName_Std</field-name>
            <field-type>string</field-type>
            <size>40</size>
            <updateable>true</updateable>
            <required>false</required>
            <code-module></code-module>
            <pattern></pattern>
            <key-type>false</key-type>
        </fields>
        <fields>
            <field-name>LastName_Phon</field-name>
            <field-type>string</field-type>
            <size>8</size>
            <updateable>true</updateable>
            <required>false</required>
            <code-module></code-module>
            <pattern></pattern>
            <key-type>false</key-type>
        </fields>
        <fields>
            <field-name>Suffix</field-name>
            <field-type>string</field-type>
            <size>35</size>
            <updateable>true</updateable>
            <required>false</required>
            <code-module></code-module>
            <pattern></pattern>
            <key-type>false</key-type>
        </fields>
        <fields>
            <field-name>Title</field-name>
            <field-type>string</field-type>
            <size>8</size>
            <updateable>true</updateable>
            <required>false</required>
            <code-module>TITLE</code-module>
            <pattern></pattern>
            <key-type>false</key-type>
        </fields>
        <fields>
            <field-name>MedicareNo</field-name>
            <field-type>string</field-type>
            <size>30</size>
            <updateable>true</updateable>
            <required>true</required>
            <code-module></code-module>
            <pattern></pattern>
            <key-type>false</key-type>
        </fields>
        <fields>
            <field-name>DOB</field-name>
            <field-type>date</field-type>
            <size>12</size>
            <updateable>true</updateable>
            <required>true</required>
            <code-module></code-module>
            <pattern></pattern>
            <key-type>false</key-type>
        </fields>
        <fields>
            <field-name>Death</field-name>
            <field-type>string</field-type>
            <size>1</size>
            <updateable>true</updateable>
            <required>false</required>
            <code-module></code-module>
            <pattern></pattern>
            <key-type>false</key-type>
        </fields>
        <fields>
            <field-name>Gender</field-name>
            <field-type>string</field-type>
            <size>8</size>
            <updateable>true</updateable>
            <required>true</required>
            <code-module>GENDER</code-module>
            <pattern></pattern>
            <key-type>false</key-type>
        </fields>
        <fields>
            <field-name>MStatus</field-name>
            <field-type>string</field-type>
            <size>8</size>
            <updateable>true</updateable>
            <required>false</required>
            <code-module>MSTATUS</code-module>
            <pattern></pattern>
            <key-type>false</key-type>
        </fields>
        <fields>
            <field-name>IndigStatus</field-name>
            <field-type>string</field-type>
            <size>50</size>
            <updateable>true</updateable>
            <required>false</required>
            <code-module>INDIGST</code-module>
            <pattern></pattern>
            <key-type>false</key-type>
        </fields>
        <fields>
            <field-name>Religion</field-name>
            <field-type>string</field-type>
            <size>8</size>
            <updateable>true</updateable>
            <required>false</required>
            <code-module>RELIGION</code-module>
            <pattern></pattern>
            <key-type>false</key-type>
        </fields>
        <fields>
            <field-name>Language</field-name>
            <field-type>string</field-type>
            <size>8</size>
            <updateable>true</updateable>
            <required>false</required>
            <code-module>LANGUAGE</code-module>
            <pattern></pattern>
            <key-type>false</key-type>
        </fields>
        <fields>
            <field-name>Maiden</field-name>
            <field-type>string</field-type>
            <size>40</size>
            <updateable>true</updateable>
            <required>false</required>
            <code-module></code-module>
            <pattern></pattern>
            <key-type>false</key-type>
        </fields>
        <fields>
            <field-name>PobCountry</field-name>
            <field-type>string</field-type>
            <size>20</size>
            <updateable>true</updateable>
            <required>false</required>
            <code-module>COUNTRY</code-module>
            <pattern></pattern>
            <key-type>false</key-type>
        </fields>
        <fields>
            <field-name>DVAColour</field-name>
            <field-type>string</field-type>
            <size>8</size>
            <updateable>true</updateable>
            <required>false</required>
            <code-module>DVACOLOR</code-module>
            <pattern></pattern>
            <key-type>false</key-type>
        </fields>
        <fields>
            <field-name>Status</field-name>
            <field-type>string</field-type>
            <size>8</size>
            <updateable>true</updateable>
            <required>false</required>
            <code-module></code-module>
            <pattern></pattern>
            <key-type>false</key-type>
        </fields>
        <fields>
            <field-name>Dod</field-name>
            <field-type>date</field-type>
            <size>12</size>
            <updateable>true</updateable>
            <required>false</required>
            <code-module></code-module>
            <pattern></pattern>
            <key-type>false</key-type>
        </fields>
        <fields>
            <field-name>DeathCertificate</field-name>
            <field-type>string</field-type>
            <size>10</size>
            <updateable>true</updateable>
            <required>false</required>
            <code-module></code-module>
            <pattern></pattern>
            <key-type>false</key-type>
        </fields>
        <fields>
            <field-name>RepatriationNo</field-name>
            <field-type>string</field-type>
            <size>10</size>
            <updateable>true</updateable>
            <required>false</required>
            <code-module></code-module>
            <pattern></pattern>
            <key-type>false</key-type>
        </fields>
        <fields>
            <field-name>PensionNo</field-name>
            <field-type>string</field-type>
            <size>8</size>
            <updateable>true</updateable>
            <required>false</required>
            <code-module></code-module>
            <pattern></pattern>
            <key-type>false</key-type>
        </fields>
        <fields>
            <field-name>PensionExpDate</field-name>
            <field-type>date</field-type>
            <size>8</size>
            <updateable>true</updateable>
            <required>false</required>
            <code-module></code-module>
            <pattern></pattern>
