=== ahimanikya/FrescoMDM/index-core/src/main/resources/schema/update.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
 # DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 #
 # Copyright 2003-2007 Sun Microsystems, Inc. All Rights Reserved.
 #
 # The contents of this file are subject to the terms of the Common 
 # Development and Distribution License ("CDDL")(the "License"). You 
 # may not use this file except in compliance with the License.
 #
 # You can obtain a copy of the License at
 # https://open-dm-mi.dev.java.net/cddl.html
 # or open-dm-mi/bootstrap/legal/license.txt. See the License for the 
 # specific language governing permissions and limitations under the  
 # License.  
 #
 # When distributing the Covered Code, include this CDDL Header Notice 
 # in each file and include the License file at
 # open-dm-mi/bootstrap/legal/license.txt.
 # If applicable, add the following below this CDDL Header, with the 
 # fields enclosed by brackets [] replaced by your own identifying 
 # information: "Portions Copyrighted [year] [name of copyright owner]"
-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="Configuration">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="SurvivorHelperConfig"/>
				<xs:element ref="WeightedCalculator" maxOccurs="unbounded"/>
				<xs:element ref="UpdateManagerConfig"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="EnterpriseCreatePolicy" type="xs:string"/>
	<xs:element name="EnterpriseMergePolicy" type="xs:string"/>
	<xs:element name="EnterpriseUnmergePolicy" type="xs:string"/>
	<xs:element name="EnterpriseUpdatePolicy" type="xs:string"/>
	<xs:element name="SkipUpdateIfNoChange" type="xs:boolean"/>
	<xs:element name="SurvivorHelperConfig">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="helper-class"/>
				<xs:element ref="default-survivor-strategy"/>
				<xs:element ref="candidate-definitions"/>
			</xs:sequence>
			<xs:attribute name="module-name" type="xs:string" use="required"/>
			<xs:attribute name="parser-class" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="SystemMergePolicy" type="xs:string"/>
	<xs:element name="SystemUnmergePolicy" type="xs:string"/>
	<xs:element name="UndoAssumeMatchPolicy">
		<xs:complexType/>
	</xs:element>
	<xs:element name="UpdateManagerConfig">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="EnterpriseMergePolicy"/>
				<xs:element ref="EnterpriseUnmergePolicy"/>
				<xs:element ref="EnterpriseUpdatePolicy"/>
				<xs:element ref="EnterpriseCreatePolicy"/>
				<xs:element ref="SystemMergePolicy"/>
				<xs:element ref="SystemUnmergePolicy"/>
				<xs:element ref="UndoAssumeMatchPolicy"/>
				<xs:element ref="SkipUpdateIfNoChange"/>
			</xs:sequence>
			<xs:attribute name="module-name" type="xs:string" use="required"/>
			<xs:attribute name="parser-class" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="WeightedCalculator">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="candidate-field" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="default-parameters"/>
			</xs:sequence>
			<xs:attribute name="module-name" type="xs:string" use="required"/>
			<xs:attribute name="parser-class" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="candidate-definitions">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="candidate-field" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="candidate-field">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="survivor-strategy" minOccurs="0"/>
				<xs:element ref="parameter" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="default-parameters">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="parameter" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="default-survivor-strategy">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="strategy-class"/>
				<xs:element ref="parameters"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="helper-class" type="xs:string"/>
	<xs:element name="parameter">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="parameter-name" minOccurs="0"/>
				<xs:element ref="parameter-type" minOccurs="0"/>
				<xs:element ref="parameter-value" minOccurs="0"/>
				<xs:element ref="quality" minOccurs="0"/>
				<xs:element ref="preference" minOccurs="0"/>
				<xs:element ref="utility" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="parameter-name" type="xs:string"/>
	<xs:element name="parameter-type" type="xs:string"/>
	<xs:element name="parameter-value" type="xs:string"/>
	<xs:element name="parameters">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="parameter"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="preference" type="xs:string"/>
	<xs:element name="quality" type="xs:string"/>
	<xs:element name="strategy-class">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="survivor-strategy">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="strategy-class"/>
				<xs:element ref="parameters" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="utility" type="xs:decimal"/>
</xs:schema>

=== ahimanikya/FrescoMDM/index-core/src/test/java/com/sun/mdm/index/survivorcalculator/config/update2.xml
<?xml version="1.0" encoding="UTF-8"?>
<Configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema/update.xsd">
	<SurvivorHelperConfig module-name="SurvivorHelper" parser-class="com.sun.mdm.index.configurator.impl.SurvivorHelperConfig">
		<helper-class>com.sun.mdm.index.survivor.impl.DefaultSurvivorHelper</helper-class>
		<default-survivor-strategy>
			<strategy-class>com.sun.mdm.index.survivor.impl.WeightedSurvivorStrategy</strategy-class>
			<parameters>
				<parameter>
					<parameter-name>ConfigurationModuleName</parameter-name>
					<parameter-type>java.lang.String</parameter-type>
					<parameter-value>WeightedSurvivorCalculator</parameter-value>
				</parameter>
			</parameters>
		</default-survivor-strategy>
		<candidate-definitions>
			<candidate-field name="Person.PersonCatCode"/>
			<candidate-field name="Person.LastName"/>
			<candidate-field name="Person.FirstName"/>
			<candidate-field name="Person.MiddleName"/>
			<candidate-field name="Person.Suffix"/>
			<candidate-field name="Person.Title"/>
			<candidate-field name="Person.DOB"/>
			<candidate-field name="Person.Death"/>
			<candidate-field name="Person.Gender"/>
			<candidate-field name="Person.MStatus"/>
			<candidate-field name="Person.SSN"/>
			<candidate-field name="Person.Race"/>
			<candidate-field name="Person.Ethnic"/>
			<candidate-field name="Person.Religion"/>
			<candidate-field name="Person.Language"/>
			<candidate-field name="Person.SpouseName"/>
			<candidate-field name="Person.MotherName"/>
			<candidate-field name="Person.MotherMN"/>
			<candidate-field name="Person.FatherName"/>
			<candidate-field name="Person.Maiden"/>
			<candidate-field name="Person.PobCity"/>
			<candidate-field name="Person.PobState"/>
			<candidate-field name="Person.PobCountry"/>
			<candidate-field name="Person.VIPFlag"/>
			<candidate-field name="Person.VetStatus"/>
			<candidate-field name="Person.FnamePhoneticCode"/>
			<candidate-field name="Person.LnamePhoneticCode"/>
			<candidate-field name="Person.MnamePhoneticCode"/>
			<candidate-field name="Person.MotherMNPhoneticCode"/>
			<candidate-field name="Person.MaidenPhoneticCode"/>
			<candidate-field name="Person.SpousePhoneticCode"/>
			<candidate-field name="Person.MotherPhoneticCode"/>
			<candidate-field name="Person.FatherPhoneticCode"/>
			<candidate-field name="Person.DriversLicense"/>
			<candidate-field name="Person.DriversLicenseSt"/>
			<candidate-field name="Person.Dod"/>
			<candidate-field name="Person.DeathCertificate"/>
			<candidate-field name="Person.Nationality"/>
			<candidate-field name="Person.Citizenship"/>
			<candidate-field name="Person.PensionNo"/>
			<candidate-field name="Person.PensionExpDate"/>
			<candidate-field name="Person.RepatriationNo"/>
			<candidate-field name="Person.DistrictOfResidence"/>
			<candidate-field name="Person.LgaCode"/>
			<candidate-field name="Person.MilitaryBranch"/>
			<candidate-field name="Person.MilitaryRank"/>
			<candidate-field name="Person.MilitaryStatus"/>
			<candidate-field name="Person.DummyDate"/>
			<candidate-field name="Person.Class1"/>
			<candidate-field name="Person.Class2"/>
			<candidate-field name="Person.Class3"/>
			<candidate-field name="Person.Class4"/>
			<candidate-field name="Person.Class5"/>
			<candidate-field name="Person.String1"/>
			<candidate-field name="Person.String2"/>
			<candidate-field name="Person.String3"/>
			<candidate-field name="Person.String4"/>
			<candidate-field name="Person.String5"/>
			<candidate-field name="Person.String6"/>
			<candidate-field name="Person.String7"/>
			<candidate-field name="Person.String8"/>
			<candidate-field name="Person.String9"/>
			<candidate-field name="Person.String10"/>
			<candidate-field name="Person.Date1"/>
			<candidate-field name="Person.Date2"/>
			<candidate-field name="Person.Date3"/>
			<candidate-field name="Person.Date4"/>
			<candidate-field name="Person.Date5"/>
			<candidate-field name="Person.StdFirstName"/>
			<candidate-field name="Person.StdLastName"/>
			<candidate-field name="Person.StdMiddleName"/>
			<candidate-field name="Person.Phone[*].*"/>
			<candidate-field name="Person.Alias[*].*"/>
			<candidate-field name="Person.Address[*].*"/>
			<candidate-field name="Person.AuxId[*].*"/>
			<candidate-field name="Person.Comment[*].*"/>
		</candidate-definitions>
	</SurvivorHelperConfig>
	<WeightedCalculator module-name="WeightedSurvivorCalculator" parser-class="com.sun.mdm.index.configurator.impl.WeightedCalculatorConfig">
		<default-parameters>
			<parameter>
				<quality>SourceSystem</quality>
				<preference>SBYN</preference>
				<utility>100.0</utility>
			</parameter>
		</default-parameters>
	</WeightedCalculator>
	<UpdateManagerConfig module-name="UpdateManager" parser-class="com.sun.mdm.index.configurator.impl.UpdateManagerConfig">
		<EnterpriseMergePolicy>com.sun.mdm.index.update.impl.EnterpriseMergePolicy</EnterpriseMergePolicy>
		<EnterpriseUnmergePolicy>com.sun.mdm.index.update.impl.EnterpriseUnmergePolicy</EnterpriseUnmergePolicy>
		<EnterpriseUpdatePolicy>com.sun.mdm.index.update.impl.EnterpriseUpdatePolicy</EnterpriseUpdatePolicy>
		<EnterpriseCreatePolicy>com.sun.mdm.index.update.impl.EnterpriseCreatePolicy</EnterpriseCreatePolicy>
		<SystemMergePolicy>com.sun.mdm.index.update.impl.SystemMergePolicy</SystemMergePolicy>
		<SystemUnmergePolicy>com.sun.mdm.index.update.impl.SystemUnmergePolicy</SystemUnmergePolicy>
		<UndoAssumeMatchPolicy/>
		<SkipUpdateIfNoChange>true</SkipUpdateIfNoChange>
	</UpdateManagerConfig>
	<!--
	<UpdateManagerConfig module-name="UpdateManager" parser-class="com.sun.mdm.index.configurator.impl.UpdateManagerConfig">
		<EnterpriseMergePolicy/>
		<EnterpriseUnmergePolicy/>
		<EnterpriseUpdatePolicy/>
		<EnterpriseCreatePolicy/>
		<SystemMergePolicy/>
		<SystemUnmergePolicy/>
		<UndoAssumeMatchPolicy/>
	</UpdateManagerConfig>
	-->
</Configuration>

=== ahimanikya/FrescoMDM/solutions/usa-patient/USAPatient/src/Configuration/update.xml
<?xml version="1.0" encoding="UTF-8"?><Configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema/update.xsd">    <SurvivorHelperConfig module-name="SurvivorHelper" parser-class="com.sun.mdm.index.configurator.impl.SurvivorHelperConfig">        <helper-class>com.sun.mdm.index.survivor.impl.DefaultSurvivorHelper</helper-class>        <default-survivor-strategy>            <strategy-class>com.sun.mdm.index.survivor.impl.WeightedSurvivorStrategy</strategy-class>            <parameters>                <parameter>                    <parameter-name>ConfigurationModuleName</parameter-name>                    <parameter-type>java.lang.String</parameter-type>                    <parameter-value>WeightedSurvivorCalculator</parameter-value>                </parameter>            </parameters>        </default-survivor-strategy>        <candidate-definitions>            <candidate-field name="USAPatient.FirstName"/>            <candidate-field name="USAPatient.FirstName_Std"/>            <candidate-field name="USAPatient.FirstName_Phon"/>            <candidate-field name="USAPatient.MiddleName"/>            <candidate-field name="USAPatient.LastName"/>            <candidate-field name="USAPatient.LastName_Std"/>            <candidate-field name="USAPatient.LastName_Phon"/>            <candidate-field name="USAPatient.Suffix"/>            <candidate-field name="USAPatient.Title"/>            <candidate-field name="USAPatient.SSN"/>            <candidate-field name="USAPatient.DOB"/>            <candidate-field name="USAPatient.Death"/>            <candidate-field name="USAPatient.Gender"/>            <candidate-field name="USAPatient.MStatus"/>            <candidate-field name="USAPatient.Race"/>            <candidate-field name="USAPatient.Ethnic"/>            <candidate-field name="USAPatient.Religion"/>            <candidate-field name="USAPatient.Language"/>            <candidate-field name="USAPatient.SpouseName"/>            <candidate-field name="USAPatient.MotherName"/>            <candidate-field name="USAPatient.MotherMN"/>            <candidate-field name="USAPatient.FatherName"/>            <candidate-field name="USAPatient.Maiden"/>            <candidate-field name="USAPatient.PobCity"/>            <candidate-field name="USAPatient.PobState"/>            <candidate-field name="USAPatient.PobCountry"/>            <candidate-field name="USAPatient.VIPFlag"/>            <candidate-field name="USAPatient.VetStatus"/>            <candidate-field name="USAPatient.Status"/>            <candidate-field name="USAPatient.DriverLicense"/>            <candidate-field name="USAPatient.DriverLicenseSt"/>            <candidate-field name="USAPatient.Dod"/>            <candidate-field name="USAPatient.DeathCertificate"/>            <candidate-field name="USAPatient.Nationality"/>            <candidate-field name="USAPatient.Citizenship"/>            <candidate-field name="USAPatient.RepatriationNo"/>            <candidate-field name="USAPatient.MilitaryBranch"/>            <candidate-field name="USAPatient.MilitaryRank"/>            <candidate-field name="USAPatient.MilitaryStatus"/>            <candidate-field name="USAPatient.DistrictOfResidence"/>            <candidate-field name="USAPatient.Alias[*].*"/>            <candidate-field name="USAPatient.Address[*].*"/>            <candidate-field name="USAPatient.Phone[*].*"/>            <candidate-field name="USAPatient.ExistingCon[*].*"/>            <candidate-field name="USAPatient.Contact[*].*"/>            <candidate-field name="USAPatient.Insurance[*].*"/>            <candidate-field name="USAPatient.Comment[*].*"/>            <candidate-field name="USAPatient.AuxId[*].*"/>        </candidate-definitions>    </SurvivorHelperConfig>    <WeightedCalculator module-name="WeightedSurvivorCalculator" parser-class="com.sun.mdm.index.configurator.impl.WeightedCalculatorConfig">        <default-parameters>            <parameter>                <quality>SourceSystem</quality>                <preference>SUN</preference>                <utility>100.0</utility>            </parameter>            <parameter>                <quality>MostRecentModified</quality>                <utility>75.0</utility>            </parameter>        </default-parameters>    </WeightedCalculator>    <UpdateManagerConfig module-name="UpdateManager" parser-class="com.sun.mdm.index.configurator.impl.UpdateManagerConfig">        <EnterpriseMergePolicy></EnterpriseMergePolicy>        <EnterpriseUnmergePolicy></EnterpriseUnmergePolicy>        <EnterpriseUpdatePolicy></EnterpriseUpdatePolicy>        <EnterpriseCreatePolicy></EnterpriseCreatePolicy>        <SystemMergePolicy></SystemMergePolicy>        <SystemUnmergePolicy></SystemUnmergePolicy>        <UndoAssumeMatchPolicy></UndoAssumeMatchPolicy>        <SkipUpdateIfNoChange>true</SkipUpdateIfNoChange>    </UpdateManagerConfig></Configuration>

=== ahimanikya/FrescoMDM/solutions/aus-patient/AUSPatient/src/Configuration/update.xml
<?xml version="1.0" encoding="UTF-8"?><Configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema/update.xsd">    <SurvivorHelperConfig module-name="SurvivorHelper" parser-class="com.sun.mdm.index.configurator.impl.SurvivorHelperConfig">        <helper-class>com.sun.mdm.index.survivor.impl.DefaultSurvivorHelper</helper-class>        <default-survivor-strategy>            <strategy-class>com.sun.mdm.index.survivor.impl.WeightedSurvivorStrategy</strategy-class>            <parameters>                <parameter>                    <parameter-name>ConfigurationModuleName</parameter-name>                    <parameter-type>java.lang.String</parameter-type>                    <parameter-value>WeightedSurvivorCalculator</parameter-value>                </parameter>            </parameters>        </default-survivor-strategy>        <candidate-definitions>            <candidate-field name="AUSPatient.Category"/>            <candidate-field name="AUSPatient.FirstName"/>            <candidate-field name="AUSPatient.FirstName_Std"/>            <candidate-field name="AUSPatient.FirstName_Phon"/>            <candidate-field name="AUSPatient.MiddleName"/>            <candidate-field name="AUSPatient.MiddleName_Std"/>            <candidate-field name="AUSPatient.MiddleName_Phon"/>            <candidate-field name="AUSPatient.LastName"/>            <candidate-field name="AUSPatient.LastName_Std"/>            <candidate-field name="AUSPatient.LastName_Phon"/>            <candidate-field name="AUSPatient.Suffix"/>            <candidate-field name="AUSPatient.Title"/>            <candidate-field name="AUSPatient.MedicareNo"/>            <candidate-field name="AUSPatient.DOB"/>            <candidate-field name="AUSPatient.Death"/>            <candidate-field name="AUSPatient.Gender"/>            <candidate-field name="AUSPatient.MStatus"/>            <candidate-field name="AUSPatient.IndigStatus"/>            <candidate-field name="AUSPatient.Religion"/>            <candidate-field name="AUSPatient.Language"/>            <candidate-field name="AUSPatient.Maiden"/>            <candidate-field name="AUSPatient.PobCountry"/>            <candidate-field name="AUSPatient.DVAColour"/>            <candidate-field name="AUSPatient.Status"/>            <candidate-field name="AUSPatient.Dod"/>            <candidate-field name="AUSPatient.DeathCertificate"/>            <candidate-field name="AUSPatient.RepatriationNo"/>            <candidate-field name="AUSPatient.PensionNo"/>            <candidate-field name="AUSPatient.PensionExpDate"/>            <candidate-field name="AUSPatient.LgaCode"/>            <candidate-field name="AUSPatient.Alias[*].*"/>            <candidate-field name="AUSPatient.Address[*].*"/>            <candidate-field name="AUSPatient.Phone[*].*"/>            <candidate-field name="AUSPatient.ExistingCon[*].*"/>            <candidate-field name="AUSPatient.Contact[*].*"/>            <candidate-field name="AUSPatient.HeathFund[*].*"/>            <candidate-field name="AUSPatient.Comment[*].*"/>            <candidate-field name="AUSPatient.AuxId[*].*"/>        </candidate-definitions>    </SurvivorHelperConfig>    <WeightedCalculator module-name="WeightedSurvivorCalculator" parser-class="com.sun.mdm.index.configurator.impl.WeightedCalculatorConfig">        <default-parameters>            <parameter>                <quality>SourceSystem</quality>                <preference>SUN</preference>                <utility>100.0</utility>            </parameter>            <parameter>                <quality>MostRecentModified</quality>                <utility>75.0</utility>            </parameter>        </default-parameters>    </WeightedCalculator>    <UpdateManagerConfig module-name="UpdateManager" parser-class="com.sun.mdm.index.configurator.impl.UpdateManagerConfig">        <EnterpriseMergePolicy></EnterpriseMergePolicy>        <EnterpriseUnmergePolicy></EnterpriseUnmergePolicy>        <EnterpriseUpdatePolicy></EnterpriseUpdatePolicy>        <EnterpriseCreatePolicy></EnterpriseCreatePolicy>        <SystemMergePolicy></SystemMergePolicy>        <SystemUnmergePolicy></SystemUnmergePolicy>        <UndoAssumeMatchPolicy></UndoAssumeMatchPolicy>        <SkipUpdateIfNoChange>true</SkipUpdateIfNoChange>    </UpdateManagerConfig></Configuration>

=== ahimanikya/FrescoMDM/solutions/usa-citizen/USACitizen/src/Configuration/update.xml
<?xml version="1.0" encoding="UTF-8"?><Configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema/update.xsd">    <SurvivorHelperConfig module-name="SurvivorHelper" parser-class="com.sun.mdm.index.configurator.impl.SurvivorHelperConfig">        <helper-class>com.sun.mdm.index.survivor.impl.DefaultSurvivorHelper</helper-class>        <default-survivor-strategy>            <strategy-class>com.sun.mdm.index.survivor.impl.WeightedSurvivorStrategy</strategy-class>            <parameters>                <parameter>                    <parameter-name>ConfigurationModuleName</parameter-name>                    <parameter-type>java.lang.String</parameter-type>                    <parameter-value>WeightedSurvivorCalculator</parameter-value>                </parameter>            </parameters>        </default-survivor-strategy>        <candidate-definitions>            <candidate-field name="USACitizen.FirstName"/>            <candidate-field name="USACitizen.FirstName_Std"/>            <candidate-field name="USACitizen.FirstName_Phon"/>            <candidate-field name="USACitizen.MiddleName"/>            <candidate-field name="USACitizen.LastName"/>            <candidate-field name="USACitizen.LastName_Std"/>            <candidate-field name="USACitizen.LastName_Phon"/>            <candidate-field name="USACitizen.Suffix"/>            <candidate-field name="USACitizen.Title"/>            <candidate-field name="USACitizen.SSN"/>            <candidate-field name="USACitizen.DOB"/>            <candidate-field name="USACitizen.Gender"/>            <candidate-field name="USACitizen.MStatus"/>            <candidate-field name="USACitizen.Race"/>            <candidate-field name="USACitizen.PobCity"/>            <candidate-field name="USACitizen.PobStateCode"/>            <candidate-field name="USACitizen.PobCountry"/>            <candidate-field name="USACitizen.DOD"/>            <candidate-field name="USACitizen.Height"/>            <candidate-field name="USACitizen.HairColor"/>            <candidate-field name="USACitizen.EyeColor"/>            <candidate-field name="USACitizen.Occupation"/>            <candidate-field name="USACitizen.Employer"/>            <candidate-field name="USACitizen.Email"/>            <candidate-field name="USACitizen.HasBirthCertificate"/>            <candidate-field name="USACitizen.Alias[*].*"/>            <candidate-field name="USACitizen.Address[*].*"/>            <candidate-field name="USACitizen.Phone[*].*"/>            <candidate-field name="USACitizen.Passport[*].*"/>            <candidate-field name="USACitizen.Id[*].*"/>            <candidate-field name="USACitizen.Family[*].*"/>            <candidate-field name="USACitizen.Contact[*].*"/>        </candidate-definitions>    </SurvivorHelperConfig>    <WeightedCalculator module-name="WeightedSurvivorCalculator" parser-class="com.sun.mdm.index.configurator.impl.WeightedCalculatorConfig">        <default-parameters>            <parameter>                <quality>SourceSystem</quality>                <preference>SUN</preference>                <utility>100.0</utility>            </parameter>            <parameter>                <quality>SourceSystem</quality>                <preference>MYSQL</preference>                <utility>100.0</utility>            </parameter>            <parameter>                <quality>MostRecentModified</quality>                <utility>75.0</utility>            </parameter>        </default-parameters>    </WeightedCalculator>    <UpdateManagerConfig module-name="UpdateManager" parser-class="com.sun.mdm.index.configurator.impl.UpdateManagerConfig">        <EnterpriseMergePolicy></EnterpriseMergePolicy>        <EnterpriseUnmergePolicy></EnterpriseUnmergePolicy>        <EnterpriseUpdatePolicy></EnterpriseUpdatePolicy>        <EnterpriseCreatePolicy></EnterpriseCreatePolicy>        <SystemMergePolicy></SystemMergePolicy>        <SystemUnmergePolicy></SystemUnmergePolicy>        <UndoAssumeMatchPolicy></UndoAssumeMatchPolicy>        <SkipUpdateIfNoChange>true</SkipUpdateIfNoChange>    </UpdateManagerConfig></Configuration>

=== ahimanikya/FrescoMDM/solutions/uk-patient/UKPatient/src/Configuration/update.xml
<?xml version="1.0" encoding="UTF-8"?><Configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema/update.xsd">    <SurvivorHelperConfig module-name="SurvivorHelper" parser-class="com.sun.mdm.index.configurator.impl.SurvivorHelperConfig">        <helper-class>com.sun.mdm.index.survivor.impl.DefaultSurvivorHelper</helper-class>        <default-survivor-strategy>            <strategy-class>com.sun.mdm.index.survivor.impl.WeightedSurvivorStrategy</strategy-class>            <parameters>                <parameter>                    <parameter-name>ConfigurationModuleName</parameter-name>                    <parameter-type>java.lang.String</parameter-type>                    <parameter-value>WeightedSurvivorCalculator</parameter-value>                </parameter>            </parameters>        </default-survivor-strategy>        <candidate-definitions>            <candidate-field name="UKPatient.Category"/>            <candidate-field name="UKPatient.Gender"/>            <candidate-field name="UKPatient.DOB"/>            <candidate-field name="UKPatient.BirthOrder"/>            <candidate-field name="UKPatient.BirthTime"/>            <candidate-field name="UKPatient.MaritalStatus"/>            <candidate-field name="UKPatient.DateOfDeath"/>            <candidate-field name="UKPatient.StatusOfDeathNoti"/>            <candidate-field name="UKPatient.Language"/>            <candidate-field name="UKPatient.EthnicCatCode"/>            <candidate-field name="UKPatient.CommonContactMeth"/>            <candidate-field name="UKPatient.ContactPref01STime"/>            <candidate-field name="UKPatient.ContactPref01ETime"/>            <candidate-field name="UKPatient.ContactPref02STime"/>            <candidate-field name="UKPatient.ContactPref02ETime"/>            <candidate-field name="UKPatient.ContactPref03STime"/>            <candidate-field name="UKPatient.ContactPref03ETime"/>            <candidate-field name="UKPatient.CommentTxt"/>            <candidate-field name="UKPatient.Name[*].*"/>            <candidate-field name="UKPatient.Address[*].*"/>            <candidate-field name="UKPatient.Telecom[*].*"/>            <candidate-field name="UKPatient.Consent[*].*"/>            <candidate-field name="UKPatient.AltContact[*].*"/>            <candidate-field name="UKPatient.AltConTele[*].*"/>            <candidate-field name="UKPatient.AuxID[*].*"/>            <candidate-field name="UKPatient.HeightWeight[*].*"/>            <candidate-field name="UKPatient.HealthID[*].*"/>        </candidate-definitions>    </SurvivorHelperConfig>    <WeightedCalculator module-name="WeightedSurvivorCalculator" parser-class="com.sun.mdm.index.configurator.impl.WeightedCalculatorConfig">        <default-parameters>            <parameter>                <quality>SourceSystem</quality>                <preference>SUN</preference>                <utility>100.0</utility>            </parameter>            <parameter>                <quality>MostRecentModified</quality>                <utility>75.0</utility>            </parameter>        </default-parameters>    </WeightedCalculator>    <UpdateManagerConfig module-name="UpdateManager" parser-class="com.sun.mdm.index.configurator.impl.UpdateManagerConfig">        <EnterpriseMergePolicy></EnterpriseMergePolicy>        <EnterpriseUnmergePolicy></EnterpriseUnmergePolicy>        <EnterpriseUpdatePolicy></EnterpriseUpdatePolicy>        <EnterpriseCreatePolicy></EnterpriseCreatePolicy>        <SystemMergePolicy></SystemMergePolicy>        <SystemUnmergePolicy></SystemUnmergePolicy>        <UndoAssumeMatchPolicy></UndoAssumeMatchPolicy>        <SkipUpdateIfNoChange>true</SkipUpdateIfNoChange>    </UpdateManagerConfig></Configuration>
