=== ahimanikya/FrescoMDM/solutions/uk-patient/UKPatient/src/Configuration/schema/midm-security.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
 # DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 #
 # Copyright 2003-2007 Sun Microsystems, Inc. All Rights Reserved.
 #
 # The contents of this file are subject to the terms of the Common 
 # Development and Distribution License ("CDDL")(the "License"). You 
 # may not use this file except in compliance with the License.
 #
 # You can obtain a copy of the License at
 # https://open-dm-mi.dev.java.net/cddl.html
 # or open-dm-mi/bootstrap/legal/license.txt. See the License for the 
 # specific language governing permissions and limitations under the  
 # License.  
 #
 # When distributing the Covered Code, include this CDDL Header Notice 
 # in each file and include the License file at
 # open-dm-mi/bootstrap/legal/license.txt.
 # If applicable, add the following below this CDDL Header, with the 
 # fields enclosed by brackets [] replaced by your own identifying 
 # information: "Portions Copyrighted [year] [name of copyright owner]"
-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
    <xs:element name="midm-security">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="roles" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="name" type="xs:string"/>
    <xs:element name="role-name" type="xs:string"/>
    <xs:element name="inherits-from" type="xs:string"/>
    
    <xs:element name="roles">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="role" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="role">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="role-name"/>
                <xs:element ref="inheritance" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="operations" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="inheritance">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="inherits-from"/>
                <xs:element ref="excluded-operations" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="operations">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="name"  minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="excluded-operations">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="name"  minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ahimanikya/FrescoMDM/solutions/aus-patient/AUSPatient/src/Configuration/midm-security.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- NOTE:  This is a sample file.  It contains the basic format for the security -->
<!-- configuration file (midm-security.xml)                                               -->
<midm-security xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema/midm-security.xsd">
    <roles>
        <role>
            <role-name>Administrator</role-name>
            <operations>
                <name>AuditLog_SearchView</name>
                <name>AuditLog_Print</name>
                <name>EO_Deactivate</name>
                <name>EO_SearchViewSBR</name>
                <name>EO_Compare</name>
                <name>EO_PrintSBR</name>
                <name>EO_Activate</name>
                <name>EO_Edit</name>
                <name>EO_Unmerge</name>
                <name>EO_PrintComparison</name>
                <name>EO_Merge</name>
                <name>EO_Create</name>
                <name>EO_ViewMergeTree</name>
                <name>EO_OverwriteSBR</name>
                <name>EO_LinkSBRFields</name>
                <name>EO_UnlinkSBRFields</name>
                <name>EO_LockSBRFields</name>
                <name>EO_UnlockSBRFields</name>
                <name>AssumedMatch_SearchView</name>
                <name>AssumedMatch_Undo</name>
                <name>AssumedMatch_Print</name>
                <name>TransLog_SearchView</name>
                <name>TransLog_Print</name>
                <name>SO_Remove</name>
                <name>SO_SearchView</name>
                <name>SO_Edit</name>
                <name>SO_Compare</name>
                <name>SO_Add</name>
                <name>SO_Unmerge</name>
                <name>SO_Merge</name>
                <name>SO_Print</name>
                <name>SO_Deactivate</name>
                <name>SO_Activate</name>
                <name>PotDup_SearchView</name>
                <name>PotDup_Print</name>
                <name>PotDup_Unresolve</name>
                <name>PotDup_ResolveUntilRecalc</name>
                <name>PotDup_ResolvePermanently</name>
                <name>Reports_View</name>
                <name>Reports_MergedRecords</name>
                <name>Reports_DeactivatedEUIDs</name>
                <name>Reports_UnmergedRecords</name>
                <name>Reports_Updates</name>
                <name>Reports_Activity</name>
                <name>Reports_Duplicates</name>
                <name>Reports_AssumedMatches</name>
                <name>Field_VIP</name>
            </operations>
        </role>
        <role>
            <role-name>Clerk</role-name>
            <operations>
                <name>EO_SearchViewSBR</name>
                <name>EO_Compare</name>
                <name>EO_PrintSBR</name>
                <name>EO_PrintComparison</name>
                <name>EO_ViewMergeTree</name>
                <name>TransLog_All</name>
                <name>SO_SearchView</name>
                <name>SO_Print</name>
                <name>PotDup_SearchView</name>
                <name>PotDup_Print</name> 
            </operations>
        </role>
        <role>
            <role-name>DataEntry</role-name>
            <inheritance>
                <inherits-from>Clerk</inherits-from>
                <excluded-operations>
                    <name>EO_ViewMergeTree</name>
                    <name>TransLog_All</name>
                </excluded-operations>
            </inheritance>
            <operations>
                <name>Reports_MergedRecords</name>
                <name>Reports_DeactivatedEUIDs</name>
            </operations>
        </role>
        <role>
            <role-name>DataEntry2</role-name>
            <inheritance>
                <inherits-from>Clerk</inherits-from>
                <excluded-operations>
                    <name>EO_ViewMergeTree</name>
                    <name>TransLog_All</name>
                </excluded-operations>
            </inheritance>
            <inheritance>
                <inherits-from>DataEntry</inherits-from>
                <excluded-operations>
                    <name>Reports_MergedRecords</name>
                    <name>Reports_DeactivatedEUIDs</name>
                </excluded-operations>
            </inheritance>
            <operations>
                <name>EO_Add</name>
            </operations>
        </role>
    </roles>
</midm-security>
