=== ahimanikya/FrescoMDM/report/src/main/resources/config/report.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT application (#PCDATA)>
<!ELEMENT appserver (#PCDATA)>
<!ELEMENT configuration (appserver, application, output-folder)>
<!ELEMENT criteria (dates, status?)>
<!ELEMENT dates EMPTY>
<!ATTLIST dates
	type (range | today | yesterday) #REQUIRED
	from-date CDATA #IMPLIED
	to-date CDATA #IMPLIED
>
<!ELEMENT status (#PCDATA)>
<!ELEMENT disable (#PCDATA)>
<!ELEMENT MasterIndexReport (configuration, reports)>
<!ELEMENT enable (#PCDATA)>
<!ELEMENT field EMPTY>
<!ATTLIST field
	path CDATA #REQUIRED
	label CDATA #REQUIRED
	width CDATA #REQUIRED
>
<!ELEMENT fields (field*)>
<!ELEMENT output-file (#PCDATA)>
<!ELEMENT output-folder (#PCDATA)>
<!ELEMENT max-result-size (#PCDATA)>
<!ELEMENT page-size (#PCDATA)> 
<!ELEMENT report (enable, output-file, max-result-size?, page-size?, criteria, fields)>
<!ATTLIST report
	name CDATA #REQUIRED
	template CDATA #REQUIRED
>
<!ELEMENT reports (report+)>

=== ahimanikya/FrescoMDM/report/src/main/resources/config/PersonMasterIndex/PersonReport.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 # DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 #
 # Copyright 2003-2007 Sun Microsystems, Inc. All Rights Reserved.
 #
 # The contents of this file are subject to the terms of the Common 
 # Development and Distribution License ("CDDL")(the "License"). You 
 # may not use this file except in compliance with the License.
 #
 # You can obtain a copy of the License at
 # https://open-dm-mi.dev.java.net/cddl.html
 # or open-dm-mi/bootstrap/legal/license.txt. See the License for the 
 # specific language governing permissions and limitations under the  
 # License.  
 #
 # When distributing the Covered Code, include this CDDL Header Notice 
 # in each file and include the License file at
 # open-dm-mi/bootstrap/legal/license.txt.
 # If applicable, add the following below this CDDL Header, with the 
 # fields enclosed by brackets [] replaced by your own identifying 
 # information: "Portions Copyrighted [year] [name of copyright owner]"
-->

<!DOCTYPE MasterIndexReport SYSTEM "../report.dtd">
<MasterIndexReport>
	<configuration>
        <!---SUN Application Server -->
        <appserver>corbaname:iiop:localhost:18002</appserver>
        <!---IBM Websphere Application Server-->
        <!--appserver>corbaname:iiop:localhost:2809/NameServiceServerRoot</appserver-->
		<application>Person</application>
		<output-folder>C:\temp</output-folder>
	</configuration>
	<reports>
		<report name="Assumed Match Today" template="Assumed Match">
			<enable>true</enable>
			<output-file>assumed_match_t.txt</output-file>
			<max-result-size>0</max-result-size>
			<page-size>25</page-size>
			<criteria>
				<dates type="today" from-date="" to-date=""/>
			</criteria>
			<fields>
				<field path="Person.FirstName" label="First Name" width="10"/>
				<field path="Person.LastName" label="Last Name" width="10"/>
				<field path="Person.SSN" label="SSN" width="9"/>
				<field path="Person.DOB" label="DOB" width="10"/>
				<field path="Person.Address.AddressLine1" label="AddressLine1" width="30"/>
				<field path="Person.Address.AddressLine2" label="AddressLine2" width="30"/>
			</fields>
		</report>
		<report name="Potential Duplicate Today" template="Potential Duplicate">
			<enable>true</enable>
			<output-file>pot_dup_t.txt</output-file>
			<max-result-size>0</max-result-size>
			<page-size>25</page-size>
			<criteria>
				<dates type="today" from-date="" to-date=""/>
				<status></status>
			</criteria>
			<fields>
				<field path="Person.FirstName" label="First Name" width="10"/>
				<field path="Person.LastName" label="Last Name" width="10"/>
				<field path="Person.SSN" label="SSN" width="9"/>
				<field path="Person.DOB" label="DOB" width="10"/>
				<field path="Person.Address.AddressLine1" label="AddressLine1" width="30"/>
				<field path="Person.Address.AddressLine2" label="AddressLine2" width="30"/>
			</fields>
		</report>
		<report name="Deactivated Today" template="Deactivated">
			<enable>true</enable>
			<output-file>deactivated_t.txt</output-file>
			<max-result-size>0</max-result-size>
			<page-size>25</page-size>
			<criteria>
				<dates type="today" from-date="" to-date=""/>
			</criteria>
			<fields>
				<field path="Person.FirstName" label="First Name" width="10"/>
				<field path="Person.LastName" label="Last Name" width="10"/>
				<field path="Person.SSN" label="SSN" width="9"/>
				<field path="Person.DOB" label="DOB" width="10"/>
				<field path="Person.Address.AddressLine1" label="AddressLine1" width="30"/>
				<field path="Person.Address.AddressLine2" label="AddressLine2" width="30"/>
			</fields>
		</report>
		<report name="Merged Today" template="Merged">
			<enable>true</enable>
			<output-file>merged_t.txt</output-file>
			<max-result-size>0</max-result-size>
			<page-size>25</page-size>
			<criteria>
				<dates type="today" from-date="" to-date=""/>
			</criteria>
			<fields>
				<field path="Person.FirstName" label="First Name" width="10"/>
				<field path="Person.LastName" label="Last Name" width="10"/>
				<field path="Person.SSN" label="SSN" width="9"/>
				<field path="Person.DOB" label="DOB" width="10"/>
				<field path="Person.Address.AddressLine1" label="AddressLine1" width="30"/>
				<field path="Person.Address.AddressLine2" label="AddressLine2" width="30"/>
			</fields>
		</report>
		<report name="Unmerged Today" template="Unmerged">
			<enable>true</enable>
			<output-file>unmerged_t.txt</output-file>
			<max-result-size>0</max-result-size>
			<page-size>25</page-size>
			<criteria>
				<dates type="today" from-date="" to-date=""/>
			</criteria>
			<fields>
				<field path="Person.FirstName" label="First Name" width="10"/>
				<field path="Person.LastName" label="Last Name" width="10"/>
				<field path="Person.SSN" label="SSN" width="9"/>
				<field path="Person.DOB" label="DOB" width="10"/>
				<field path="Person.Address.AddressLine1" label="AddressLine1" width="15"/>
				<field path="Person.Phone.Phone" label="Phone" width="15"/>
			</fields>
		</report>
		<report name="Update Today" template="Update">
			<enable>true</enable>
			<output-file>update_t.txt</output-file>
			<max-result-size>0</max-result-size>
			<page-size>25</page-size>
			<criteria>
				<dates type="today" from-date="" to-date=""/>
			</criteria>
			<fields>
				<field path="Person.FirstName" label="First Name" width="10"/>
				<field path="Person.LastName" label="Last Name" width="10"/>
				<field path="Person.SSN" label="SSN" width="9"/>
				<field path="Person.DOB" label="DOB" width="10"/>
				<field path="Person.Address.AddressLine1" label="AddressLine1" width="30"/>
				<field path="Person.Address.AddressLine2" label="AddressLine2" width="30"/>
			</fields>
		</report>
		<report name="Transaction Audit" template="Weekly Activity">
			<enable>true</enable>
			<output-file>weekly_audit.txt</output-file>
			<max-result-size>0</max-result-size>
			<criteria>
				<dates type="today" from-date="" to-date=""/>
			</criteria>
			<fields></fields>
		</report>
		<report name="Transaction Summary" template="Monthly Activity">
			<enable>true</enable>
			<output-file>monthly_stats.txt</output-file>
			<max-result-size>0</max-result-size>
			<criteria>
				<dates type="range" from-date="20040301" to-date="20040331"/>
			</criteria>
			<fields></fields>
		</report>
		<report name="Transaction Summary" template="Yearly Activity">
			<enable>true</enable>
			<output-file>yearly_stats.txt</output-file>
			<max-result-size>0</max-result-size>
			<criteria>
				<dates type="range" from-date="20040101" to-date="20041231"/>
			</criteria>
			<fields></fields>
		</report>
	</reports>
</MasterIndexReport>
