=== ahimanikya/FrescoMDM/solutions/usa-citizen/USACitizen/src/Configuration/schema/query.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
 # DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 #
 # Copyright 2003-2007 Sun Microsystems, Inc. All Rights Reserved.
 #
 # The contents of this file are subject to the terms of the Common 
 # Development and Distribution License ("CDDL")(the "License"). You 
 # may not use this file except in compliance with the License.
 #
 # You can obtain a copy of the License at
 # https://open-dm-mi.dev.java.net/cddl.html
 # or open-dm-mi/bootstrap/legal/license.txt. See the License for the 
 # specific language governing permissions and limitations under the  
 # License.  
 #
 # When distributing the Covered Code, include this CDDL Header Notice 
 # in each file and include the License file at
 # open-dm-mi/bootstrap/legal/license.txt.
 # If applicable, add the following below this CDDL Header, with the 
 # fields enclosed by brackets [] replaced by your own identifying 
 # information: "Portions Copyrighted [year] [name of copyright owner]"
-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="Configuration">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="QueryBuilderConfig"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="QueryBuilderConfig">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="query-builder" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="module-name" type="xs:string" use="required"/>
			<xs:attribute name="parser-class" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="block-definition">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="hint" minOccurs="0"/>
				<xs:element ref="block-rule"/>
			</xs:sequence>
			<xs:attribute name="number" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN"/>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="hint" type="xs:string"/>
	<xs:element name="block-rule">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="equals" minOccurs="0" maxOccurs="unbounded"/>
                                <xs:element ref="not-equals" minOccurs="0" maxOccurs="unbounded"/>
                                <xs:element ref="greater-than-or-equal" minOccurs="0" maxOccurs="unbounded"/>
                                <xs:element ref="less-than-or-equal" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="range" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="range">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="field"/>
				<xs:element ref="source"/>
				<xs:element ref="default" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="default">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="lower-bound" minOccurs="0"/>
				<xs:element ref="upper-bound" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="lower-bound">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="bound-value">
					<xs:attribute name="type" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="constant"/>
								<xs:enumeration value="offset"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="upper-bound">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="bound-value">
					<xs:attribute name="type" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="constant"/>
								<xs:enumeration value="offset"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="bound-value">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="config">
		<xs:complexType>
			<xs:choice>
				<xs:element ref="option"/>
				<xs:element ref="block-definition" maxOccurs="unbounded"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="equals" type="sourceType">
	</xs:element>
	<xs:element name="not-equals" type="sourceType">
	</xs:element>
        <xs:element name="greater-than-or-equal" type="sourceType">
	</xs:element>
	<xs:element name="less-than-or-equal" type="sourceType">
	</xs:element>

	<xs:element name="field">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="option">
		<xs:complexType>
			<xs:attribute name="key" type="xs:string" use="required"/>
			<xs:attribute name="value" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="false"/>
						<xs:enumeration value="true"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="query-builder">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="config"/>
			</xs:sequence>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="class" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="parser-class" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="standardize" type="xs:boolean" use="required"/>
			<xs:attribute name="phoneticize" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="false"/>
						<xs:enumeration value="true"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="source">
            <xs:simpleType>
                <xs:restriction base="xs:string"/>
            </xs:simpleType>
        </xs:element>
	<xs:element name="constant">
            <xs:simpleType>
                <xs:restriction base="xs:string"/>
            </xs:simpleType>
	</xs:element>
	<xs:element name="offset">
            <xs:simpleType>
                <xs:restriction base="xs:string"/>
            </xs:simpleType>
	</xs:element>
        <xs:complexType name="sourceType">
            <xs:sequence>
		<xs:element ref="field"/>
                <xs:choice>
                    <xs:element ref="source"/>
                    <xs:element ref="constant"/>
                    <xs:element ref="offset"/>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>

</xs:schema>

=== ahimanikya/FrescoMDM/index-core/src/test/config/query1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.1 U (http://www.xmlspy.com) by seebeyond (SeeBeyond) -->
<Configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="sbyn:SeeBeyond/eView/schema/query.xsd">
	<QueryBuilderConfig module-name="QueryBuilder" parser-class="com.sun.mdm.index.configurator.impl.querybuilder.QueryBuilderConfiguration">
		<query-builder name="ALPHA-SEARCH" class="com.sun.mdm.index.querybuilder.BasicQueryBuilder" parser-class="com.sun.mdm.index.configurator.impl.querybuilder.KeyValueConfiguration" standardize="true" phoneticize="false">
			<config>
				<option key="UseWildcard" value="true"/>
			</config>
		</query-builder>
		<query-builder name="PHONETIC-SEARCH" class="com.sun.mdm.index.querybuilder.BasicQueryBuilder" parser-class="com.sun.mdm.index.configurator.impl.querybuilder.KeyValueConfiguration" standardize="true" phoneticize="true">
			<config>
				<option key="UseWildcard" value="false"/>
			</config>
		</query-builder>
		<query-builder name="BLOCKER-SEARCH" class="com.sun.mdm.index.querybuilder.BlockerQueryBuilder" parser-class="com.sun.mdm.index.configurator.impl.blocker.BlockerConfig" standardize="true" phoneticize="true">
			<config>
				<block-definition number="ID000001">
					<block-rule>
						<equals>
							<field>Enterprise.SystemSBR.Person.FnamePhoneticCode</field>
							<source>Person.FnamePhoneticCode</source>
						</equals>
						<range>
							<field>Enterprise.SystemSBR.Person.DOB</field>
							<source>Person.DOB</source>
						</range>
						<equals>
							<field>Enterprise.SystemSBR.Person.Gender</field>
							<source>Person.Gender</source>
						</equals>
					</block-rule>
				</block-definition>
				<block-definition number="ID000002">
					<block-rule>
						<range>
							<field>Enterprise.SystemSBR.Person.Address.PostalCode</field>
							<source>Person.Address.PostalCode</source>
						</range>
					</block-rule>
				</block-definition>
			</config>
		</query-builder>
		<query-builder name="BLOCKER-SEARCH2" class="com.sun.mdm.index.querybuilder.BlockerQueryBuilder" parser-class="com.sun.mdm.index.configurator.impl.blocker.BlockerConfig" standardize="true" phoneticize="true">
			<config>
				<block-definition number="ID000001">
					<block-rule>
						<range>
 							<field>Enterprise.SystemSBR.Person.DOB</field>
 							<source>Person.DOB</source>
 							<default>
    							<lower-bound type="offset">-355</lower-bound>
                        <upper-bound type="offset">10</upper-bound>
    						</default>    	
   					</range>
					</block-rule>
				</block-definition>
			</config>
		</query-builder>		
		<query-builder name="BLOCKER-SEARCH3" class="com.sun.mdm.index.querybuilder.BlockerQueryBuilder" parser-class="com.sun.mdm.index.configurator.impl.blocker.BlockerConfig" standardize="true" phoneticize="true">
			<config>
				<block-definition number="ID000001">
					<block-rule>
						<range>
 							<field>Enterprise.SystemSBR.Person.DOB</field>
 							<source>Person.DOB</source>
 							<default>
    							<lower-bound type="constant">1974-01-09</lower-bound>
                        <upper-bound type="constant">1974-01-11</upper-bound>
    						</default>    	
   					</range>
					</block-rule>
				</block-definition>
			</config>
		</query-builder>
		<query-builder name="BLOCKER-SEARCH-MULTI-VAL" class="com.sun.mdm.index.querybuilder.BlockerQueryBuilder" parser-class="com.sun.mdm.index.configurator.impl.blocker.BlockerConfig" standardize="true" phoneticize="true">
			<config>
				<block-definition number="ID000000">
					<block-rule>
						<equals>
							<field>Enterprise.SystemSBR.Person.FirstName</field>
							<source>Person.FirstName</source>
						</equals>
						<equals>
							<field>Enterprise.SystemSBR.Person.LastName</field>
							<source>Person.LastName</source>
						</equals>
					</block-rule>
				</block-definition>
				<block-definition number="ID000001">
					<block-rule>
						<equals>
							<field>Enterprise.SystemSBR.Person.SSN</field>
							<source>Person.SSN</source>
						</equals>
					</block-rule>
				</block-definition>
				<block-definition number="ID000002">
					<block-rule>
						<equals>
							<field>Enterprise.SystemSBR.Person.Address.City</field>
							<source>Person.Address[*].City</source>
						</equals>
						<equals>
							<field>Enterprise.SystemSBR.Person.Address.StateCode</field>
							<source>Person.Address[*].StateCode</source>
						</equals>
						<equals>
							<field>Enterprise.SystemSBR.Person.DOB</field>
							<source>Person.DOB</source>
						</equals>
						
					</block-rule>
				</block-definition>
			</config>
		</query-builder>
		<query-builder name="BLOCKER-SEARCH-MULTI-VAL-RANGE" class="com.sun.mdm.index.querybuilder.BlockerQueryBuilder" parser-class="com.sun.mdm.index.configurator.impl.blocker.BlockerConfig" standardize="true" phoneticize="true">
			<config>
				<block-definition number="ID000000">
					<block-rule>
						<equals>
							<field>Enterprise.SystemSBR.Person.FirstName</field>
							<source>Person.FirstName</source>
						</equals>
						<equals>
							<field>Enterprise.SystemSBR.Person.LastName</field>
							<source>Person.LastName</source>
						</equals>
					</block-rule>
				</block-definition>
				<block-definition number="ID000001">
					<block-rule>
						<equals>
							<field>Enterprise.SystemSBR.Person.SSN</field>
							<source>Person.SSN</source>
						</equals>
					</block-rule>
				</block-definition>
				<block-definition number="ID000002">
					<block-rule>
						<equals>
							<field>Enterprise.SystemSBR.Person.Address.City</field>
							<source>Person.Address[*].City</source>
						</equals>
						<equals>
							<field>Enterprise.SystemSBR.Person.Address.StateCode</field>
							<source>Person.Address[*].StateCode</source>
						</equals>
						<range>
							<field>Enterprise.SystemSBR.Person.DOB</field>
							<source>Person.DOB</source>
						</range>
						
					</block-rule>
				</block-definition>
			</config>
		</query-builder>
		<query-builder name="BLOCKER-SEARCH-RANGE-WITH-CONSTANTS" class="com.sun.mdm.index.querybuilder.BlockerQueryBuilder" parser-class="com.sun.mdm.index.configurator.impl.blocker.BlockerConfig" standardize="true" phoneticize="true">
			<config>
				<block-definition number="ID000000">
					<block-rule>
						<equals>
							<field>Enterprise.SystemSBR.Person.FirstName</field>
							<source>Person.FirstName</source>
						</equals>
						<equals>
							<field>Enterprise.SystemSBR.Person.LastName</field>
							<source>Person.LastName</source>
						</equals>
					</block-rule>
				</block-definition>
				<block-definition number="ID000001">
					<block-rule>
						<equals>
							<field>Enterprise.SystemSBR.Person.SSN</field>
							<source>Person.SSN</source>
						</equals>
					</block-rule>
				</block-definition>
				<block-definition number="ID000002">
					<block-rule>
						<equals>
							<field>Enterprise.SystemSBR.Person.Address.City</field>
							<source>Person.Address[*].City</source>
						</equals>
						<equals>
							<field>Enterprise.SystemSBR.Person.Address.StateCode</field>
							<source>Person.Address[*].StateCode</source>
						</equals>
						<range>
							<field>Enterprise.SystemSBR.Person.DOB</field>
							<source>Person.DOB</source>
  							<default>
    								<lower-bound type="constant">1966-02-04</lower-bound>
    								<upper-bound type="constant">1966-02-06</upper-bound>
  							</default>
						</range>						
					</block-rule>
				</block-definition>
			</config>
		</query-builder>	
		<query-builder name="BLOCKER-SEARCH-RANGE-WITH-OFFSET" class="com.sun.mdm.index.querybuilder.BlockerQueryBuilder" parser-class="com.sun.mdm.index.configurator.impl.blocker.BlockerConfig" standardize="true" phoneticize="true">
			<config>
				<block-definition number="ID000000">
					<block-rule>
						<equals>
							<field>Enterprise.SystemSBR.Person.FirstName</field>
							<source>Person.FirstName</source>
						</equals>
						<equals>
							<field>Enterprise.SystemSBR.Person.LastName</field>
							<source>Person.LastName</source>
						</equals>
					</block-rule>
				</block-definition>
				<block-definition number="ID000001">
					<block-rule>
						<equals>
							<field>Enterprise.SystemSBR.Person.SSN</field>
							<source>Person.SSN</source>
						</equals>
					</block-rule>
				</block-definition>
				<block-definition number="ID000002">
					<block-rule>
						<equals>
							<field>Enterprise.SystemSBR.Person.Address.City</field>
							<source>Person.Address[*].City</source>
						</equals>
						<equals>
							<field>Enterprise.SystemSBR.Person.Address.StateCode</field>
							<source>Person.Address[*].StateCode</source>
						</equals>
						<range>
							<field>Enterprise.SystemSBR.Person.DOB</field>
							<source>Person.DOB</source>
  							<default>
    								<lower-bound type="offset">-1</lower-bound>
    								<upper-bound type="offset">1</upper-bound>
  							</default>
						</range>						
					</block-rule>
				</block-definition>
			</config>
		</query-builder>	
	</QueryBuilderConfig>
</Configuration>

=== ahimanikya/FrescoMDM/solutions/uk-patient/UKPatient/src/Configuration/query.xml
<?xml version="1.0" encoding="UTF-8"?><Configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema/query.xsd">    <QueryBuilderConfig module-name="QueryBuilder" parser-class="com.sun.mdm.index.configurator.impl.querybuilder.QueryBuilderConfiguration">        <query-builder name="ALPHA-SEARCH" class="com.sun.mdm.index.querybuilder.BasicQueryBuilder" parser-class="com.sun.mdm.index.configurator.impl.querybuilder.KeyValueConfiguration" standardize="false" phoneticize="false">            <config>                <option key="UseWildcard" value="true"/>            </config>        </query-builder>        <query-builder name="PHONETIC-SEARCH" class="com.sun.mdm.index.querybuilder.BasicQueryBuilder" parser-class="com.sun.mdm.index.configurator.impl.querybuilder.KeyValueConfiguration" standardize="true" phoneticize="true">            <config>                <option key="UseWildcard" value="false"/>            </config>        </query-builder>        <query-builder name="BLOCKER-SEARCH" class="com.sun.mdm.index.querybuilder.BlockerQueryBuilder" parser-class="com.sun.mdm.index.configurator.impl.blocker.BlockerConfig" standardize="true" phoneticize="true">            <config>                <block-definition  number="FamilyNameGivenNameDOB">                    <hint></hint>                    <block-rule>                        <equals>                            <field>Enterprise.SystemSBR.UKPatient.Name.FamilyName_Phon</field>                            <source>UKPatient.Name.FamilyName_Phon</source>                        </equals>                        <equals>                            <field>Enterprise.SystemSBR.UKPatient.Name.GivenName_Phon</field>                            <source>UKPatient.Name.GivenName_Phon</source>                        </equals>                        <equals>                            <field>Enterprise.SystemSBR.UKPatient.DOB</field>                            <source>UKPatient.DOB</source>                        </equals>                    </block-rule>                </block-definition>                <block-definition  number="FamilyNameDOBGender">                    <hint></hint>                    <block-rule>                        <equals>                            <field>Enterprise.SystemSBR.UKPatient.Name.GivenName</field>                            <source>UKPatient.Name.GivenName_Phon</source>                        </equals>                        <equals>                            <field>Enterprise.SystemSBR.UKPatient.Gender</field>                            <source>UKPatient.Gender</source>                        </equals>                        <equals>                            <field>Enterprise.SystemSBR.UKPatient.DOB</field>                            <source>UKPatient.DOB</source>                        </equals>                    </block-rule>                </block-definition>                <block-definition  number="DOBPostcode">                    <hint></hint>                    <block-rule>                        <equals>                            <field>Enterprise.SystemSBR.UKPatient.DOB</field>                            <source>UKPatient.DOB</source>                        </equals>                        <equals>                            <field>Enterprise.SystemSBR.UKPatient.Address.Postcode</field>                            <source>UKPatient.Address.Postcode</source>                        </equals>                    </block-rule>                </block-definition>                <block-definition  number="HealthID">                    <hint></hint>                    <block-rule>                        <equals>                            <field>Enterprise.SystemSBR.UKPatient.HealthID.IdNum</field>                            <source>UKPatient.HealthID.IdNum</source>                        </equals>                        <equals>                            <field>Enterprise.SystemSBR.UKPatient.HealthID.IdNumType</field>                            <source>UKPatient.HealthID.IdNumType</source>                        </equals>                    </block-rule>                </block-definition>            </config>        </query-builder>    </QueryBuilderConfig></Configuration>

=== ahimanikya/FrescoMDM/index-core/src/test/eindex-templates/eindex/src/Configuration/query.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.1 U (http://www.xmlspy.com) by seebeyond (SeeBeyond) -->
<Configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="sbyn:SeeBeyond/eView/schema/query.xsd">
	<QueryBuilderConfig module-name="QueryBuilder" parser-class="com.sun.mdm.index.configurator.impl.querybuilder.QueryBuilderConfiguration">
		<query-builder name="ALPHA-SEARCH" class="com.sun.mdm.index.querybuilder.BasicQueryBuilder" parser-class="com.sun.mdm.index.configurator.impl.querybuilder.KeyValueConfiguration" standardize="true" phoneticize="false">
			<config>
				<option key="UseWildcard" value="true"/>
			</config>
		</query-builder>
		<query-builder name="PHONETIC-SEARCH" class="com.sun.mdm.index.querybuilder.BasicQueryBuilder" parser-class="com.sun.mdm.index.configurator.impl.querybuilder.KeyValueConfiguration" standardize="true" phoneticize="true">
			<config>
				<option key="UseWildcard" value="false"/>
			</config>
		</query-builder>
		<query-builder name="BLOCKER-SEARCH" class="com.sun.mdm.index.querybuilder.BlockerQueryBuilder" parser-class="com.sun.mdm.index.configurator.impl.blocker.BlockerConfig" standardize="true" phoneticize="true">
			<config>
				<block-definition number="ID000000">
					<block-rule>
						<equals>
							<field>Enterprise.SystemSBR.Person.FnamePhoneticCode</field>
							<source>Person.FnamePhoneticCode</source>
						</equals>
						<equals>
							<field>Enterprise.SystemSBR.Person.LnamePhoneticCode</field>
							<source>Person.LnamePhoneticCode</source>
						</equals>
					</block-rule>
				</block-definition>
				<block-definition number="ID000001">
					<block-rule>
						<equals>
							<field>Enterprise.SystemSBR.Person.SSN</field>
							<source>Person.SSN</source>
						</equals>
					</block-rule>
				</block-definition>
				<block-definition number="ID000002">
					<block-rule>
						<equals>
							<field>Enterprise.SystemSBR.Person.FnamePhoneticCode</field>
							<source>Person.FnamePhoneticCode</source>
						</equals>
						<equals>
							<field>Enterprise.SystemSBR.Person.DOB</field>
							<source>Person.DOB</source>
						</equals>
						<equals>
							<field>Enterprise.SystemSBR.Person.Gender</field>
							<source>Person.Gender</source>
						</equals>
					</block-rule>
				</block-definition>
				<block-definition number="ID000003">
					<block-rule>
						<equals>
							<field>Enterprise.SystemSBR.Person.LnamePhoneticCode</field>
							<source>Person.LnamePhoneticCode</source>
						</equals>
						<equals>
							<field>Enterprise.SystemSBR.Person.MotherMNPhoneticCode</field>
							<source>Person.MotherMNPhoneticCode</source>
						</equals>
					</block-rule>
				</block-definition>
                <block-definition number="ID000004">
					<block-rule>
						<equals>
							<field>Enterprise.SystemSBR.Person.Alias.LnamePhoneticCode</field>
							<source>Person.LnamePhoneticCode</source>
						</equals>
						<equals>
							<field>Enterprise.SystemSBR.Person.Alias.FnamePhoneticCode</field>
							<source>Person.FnamePhoneticCode</source>
						</equals>
					</block-rule>
				</block-definition>
			</config>
		</query-builder>
		<query-builder name="BLOCKER-SEARCH2" class="com.sun.mdm.index.querybuilder.BlockerQueryBuilder" parser-class="com.sun.mdm.index.configurator.impl.blocker.BlockerConfig" standardize="true" phoneticize="true">
			<config>
				<block-definition number="ID000000">
					<block-rule>
						<equals>
							<field>Enterprise.SystemSBR.Person.FnamePhoneticCode</field>
							<source>Person.FnamePhoneticCode</source>
						</equals>
						<equals>
							<field>Enterprise.SystemSBR.Person.LnamePhoneticCode</field>
							<source>Person.LnamePhoneticCode</source>
						</equals>
					</block-rule>
				</block-definition>
				<block-definition number="ID000001">
					<block-rule>
						<equals>
							<field>Enterprise.SystemSBR.Person.Address.HouseNumber</field>
							<source>Person.Address.HouseNumber</source>
						</equals>
						<equals>
							<field>Enterprise.SystemSBR.Person.Address.StreetNamePhoneticCode</field>
							<source>Person.Address.StreetNamePhoneticCode</source>
						</equals>
					</block-rule>
				</block-definition>
				<block-definition number="ID000002">
					<block-rule>
						<equals>
							<field>Enterprise.SystemSBR.Person.Address.StreetNamePhoneticCode</field>
							<source>Person.Address.StreetNamePhoneticCode</source>
						</equals>
						<equals>
							<field>Enterprise.SystemSBR.Person.LnamePhoneticCode</field>
							<source>Person.LnamePhoneticCode</source>
						</equals>
					</block-rule>
				</block-definition>
				<block-definition number="ID000003">
					<block-rule>
						<equals>
							<field>Enterprise.SystemSBR.Person.SSN</field>
							<source>Person.SSN</source>
						</equals>
					</block-rule>
				</block-definition>
				<block-definition number="ID000004">
					<block-rule>
						<equals>
							<field>Enterprise.SystemSBR.Person.FnamePhoneticCode</field>
							<source>Person.FnamePhoneticCode</source>
						</equals>
						<equals>
							<field>Enterprise.SystemSBR.Person.Gender</field>
							<source>Person.Gender</source>
						</equals>
						<range>
							<field>Enterprise.SystemSBR.Person.DOB</field>
							<source>Person.DOB</source>
						</range>
					</block-rule>
				</block-definition>
				<block-definition number="ID000005">
					<block-rule>
						<equals>
							<field>Enterprise.SystemSBR.Person.LnamePhoneticCode</field>
							<source>Person.LnamePhoneticCode</source>
						</equals>
						<equals>
							<field>Enterprise.SystemSBR.Person.MotherMNPhoneticCode</field>
							<source>Person.MotherMNPhoneticCode</source>
						</equals>
					</block-rule>
				</block-definition>
				<block-definition number="ID000006">
					<block-rule>
						<equals>
							<field>Enterprise.SystemSBR.Person.Alias.LnamePhoneticCode</field>
							<source>Person.LnamePhoneticCode</source>
						</equals>
						<equals>
							<field>Enterprise.SystemSBR.Person.Alias.FnamePhoneticCode</field>
							<source>Person.FnamePhoneticCode</source>
						</equals>
					</block-rule>
				</block-definition>
			</config>
		</query-builder>
	</QueryBuilderConfig>
</Configuration>
