=== ahimanikya/FrescoMDM/solutions/usa-citizen/USACitizen/src/Configuration/schema/query.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
 # DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 #
 # Copyright 2003-2007 Sun Microsystems, Inc. All Rights Reserved.
 #
 # The contents of this file are subject to the terms of the Common 
 # Development and Distribution License ("CDDL")(the "License"). You 
 # may not use this file except in compliance with the License.
 #
 # You can obtain a copy of the License at
 # https://open-dm-mi.dev.java.net/cddl.html
 # or open-dm-mi/bootstrap/legal/license.txt. See the License for the 
 # specific language governing permissions and limitations under the  
 # License.  
 #
 # When distributing the Covered Code, include this CDDL Header Notice 
 # in each file and include the License file at
 # open-dm-mi/bootstrap/legal/license.txt.
 # If applicable, add the following below this CDDL Header, with the 
 # fields enclosed by brackets [] replaced by your own identifying 
 # information: "Portions Copyrighted [year] [name of copyright owner]"
-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="Configuration">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="QueryBuilderConfig"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="QueryBuilderConfig">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="query-builder" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="module-name" type="xs:string" use="required"/>
			<xs:attribute name="parser-class" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="block-definition">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="hint" minOccurs="0"/>
				<xs:element ref="block-rule"/>
			</xs:sequence>
			<xs:attribute name="number" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN"/>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="hint" type="xs:string"/>
	<xs:element name="block-rule">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="equals" minOccurs="0" maxOccurs="unbounded"/>
                                <xs:element ref="not-equals" minOccurs="0" maxOccurs="unbounded"/>
                                <xs:element ref="greater-than-or-equal" minOccurs="0" maxOccurs="unbounded"/>
                                <xs:element ref="less-than-or-equal" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="range" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="range">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="field"/>
				<xs:element ref="source"/>
				<xs:element ref="default" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="default">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="lower-bound" minOccurs="0"/>
				<xs:element ref="upper-bound" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="lower-bound">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="bound-value">
					<xs:attribute name="type" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="constant"/>
								<xs:enumeration value="offset"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="upper-bound">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="bound-value">
					<xs:attribute name="type" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="constant"/>
								<xs:enumeration value="offset"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="bound-value">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="config">
		<xs:complexType>
			<xs:choice>
				<xs:element ref="option"/>
				<xs:element ref="block-definition" maxOccurs="unbounded"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="equals" type="sourceType">
	</xs:element>
	<xs:element name="not-equals" type="sourceType">
	</xs:element>
        <xs:element name="greater-than-or-equal" type="sourceType">
	</xs:element>
	<xs:element name="less-than-or-equal" type="sourceType">
	</xs:element>

	<xs:element name="field">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="option">
		<xs:complexType>
			<xs:attribute name="key" type="xs:string" use="required"/>
			<xs:attribute name="value" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="false"/>
						<xs:enumeration value="true"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="query-builder">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="config"/>
			</xs:sequence>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="class" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="parser-class" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="standardize" type="xs:boolean" use="required"/>
			<xs:attribute name="phoneticize" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="false"/>
						<xs:enumeration value="true"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="source">
            <xs:simpleType>
                <xs:restriction base="xs:string"/>
            </xs:simpleType>
        </xs:element>
	<xs:element name="constant">
            <xs:simpleType>
                <xs:restriction base="xs:string"/>
            </xs:simpleType>
	</xs:element>
	<xs:element name="offset">
            <xs:simpleType>
                <xs:restriction base="xs:string"/>
            </xs:simpleType>
	</xs:element>
        <xs:complexType name="sourceType">
            <xs:sequence>
		<xs:element ref="field"/>
                <xs:choice>
                    <xs:element ref="source"/>
                    <xs:element ref="constant"/>
                    <xs:element ref="offset"/>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>

</xs:schema>

=== ahimanikya/FrescoMDM/solutions/usa-patient/USAPatient/src/Configuration/query.xml
<?xml version="1.0" encoding="UTF-8"?><Configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema/query.xsd">    <QueryBuilderConfig module-name="QueryBuilder" parser-class="com.sun.mdm.index.configurator.impl.querybuilder.QueryBuilderConfiguration">        <query-builder name="ALPHA-SEARCH" class="com.sun.mdm.index.querybuilder.BasicQueryBuilder" parser-class="com.sun.mdm.index.configurator.impl.querybuilder.KeyValueConfiguration" standardize="false" phoneticize="false">            <config>                <option key="UseWildcard" value="true"/>            </config>        </query-builder>        <query-builder name="PHONETIC-SEARCH" class="com.sun.mdm.index.querybuilder.BasicQueryBuilder" parser-class="com.sun.mdm.index.configurator.impl.querybuilder.KeyValueConfiguration" standardize="true" phoneticize="true">            <config>                <option key="UseWildcard" value="false"/>            </config>        </query-builder>        <query-builder name="BLOCKER-SEARCH" class="com.sun.mdm.index.querybuilder.BlockerQueryBuilder" parser-class="com.sun.mdm.index.configurator.impl.blocker.BlockerConfig" standardize="true" phoneticize="true">            <config>                <block-definition  number="FirstNameLastName">                    <hint></hint>                    <block-rule>                        <equals>                            <field>Enterprise.SystemSBR.USAPatient.FirstName_Phon</field>                            <source>USAPatient.FirstName_Phon</source>                        </equals>                        <equals>                            <field>Enterprise.SystemSBR.USAPatient.LastName_Phon</field>                            <source>USAPatient.LastName_Phon</source>                        </equals>                    </block-rule>                </block-definition>                <block-definition  number="SSN">                    <hint></hint>                    <block-rule>                        <equals>                            <field>Enterprise.SystemSBR.USAPatient.SSN</field>                            <source>USAPatient.SSN</source>                        </equals>                    </block-rule>                </block-definition>                <block-definition  number="FirstNameDOBGender">                    <hint></hint>                    <block-rule>                        <equals>                            <field>Enterprise.SystemSBR.USAPatient.FirstName_Phon</field>                            <source>USAPatient.FirstName_Phon</source>                        </equals>                        <equals>                            <field>Enterprise.SystemSBR.USAPatient.DOB</field>                            <source>USAPatient.DOB</source>                        </equals>                        <equals>                            <field>Enterprise.SystemSBR.USAPatient.Gender</field>                            <source>USAPatient.Gender</source>                        </equals>                    </block-rule>                </block-definition>            </config>        </query-builder>    </QueryBuilderConfig></Configuration>

=== ahimanikya/FrescoMDM/solutions/usa-citizen/USACitizen/src/Configuration/query.xml
<?xml version="1.0" encoding="UTF-8"?><Configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema/query.xsd">    <QueryBuilderConfig module-name="QueryBuilder" parser-class="com.sun.mdm.index.configurator.impl.querybuilder.QueryBuilderConfiguration">        <query-builder name="ALPHA-SEARCH" class="com.sun.mdm.index.querybuilder.BasicQueryBuilder" parser-class="com.sun.mdm.index.configurator.impl.querybuilder.KeyValueConfiguration" standardize="false" phoneticize="false">            <config>                <option key="UseWildcard" value="true"/>            </config>        </query-builder>        <query-builder name="PHONETIC-SEARCH" class="com.sun.mdm.index.querybuilder.BasicQueryBuilder" parser-class="com.sun.mdm.index.configurator.impl.querybuilder.KeyValueConfiguration" standardize="true" phoneticize="true">            <config>                <option key="UseWildcard" value="false"/>            </config>        </query-builder>        <query-builder name="BLOCKER-SEARCH" class="com.sun.mdm.index.querybuilder.BlockerQueryBuilder" parser-class="com.sun.mdm.index.configurator.impl.blocker.BlockerConfig" standardize="true" phoneticize="true">            <config>                <block-definition  number="FirstLastDOB">                    <hint></hint>                    <block-rule>                        <equals>                            <field>Enterprise.SystemSBR.USACitizen.FirstName_Phon</field>                            <source>USACitizen.FirstName_Phon</source>                        </equals>                        <equals>                            <field>Enterprise.SystemSBR.USACitizen.LastName_Phon</field>                            <source>USACitizen.LastName_Phon</source>                        </equals>                        <equals>                            <field>Enterprise.SystemSBR.USACitizen.DOB</field>                            <source>USACitizen.DOB</source>                        </equals>                    </block-rule>                </block-definition>                <block-definition  number="SSN">                    <hint></hint>                    <block-rule>                        <equals>                            <field>Enterprise.SystemSBR.USACitizen.SSN</field>                            <source>USACitizen.SSN</source>                        </equals>                    </block-rule>                </block-definition>                <block-definition  number="FirstDOBGender">                    <hint></hint>                    <block-rule>                        <equals>                            <field>Enterprise.SystemSBR.USACitizen.FirstName_Phon</field>                            <source>USACitizen.FirstName_Phon</source>                        </equals>                        <equals>                            <field>Enterprise.SystemSBR.USACitizen.DOB</field>                            <source>USACitizen.DOB</source>                        </equals>                        <equals>                            <field>Enterprise.SystemSBR.USACitizen.Gender</field>                            <source>USACitizen.Gender</source>                        </equals>                    </block-rule>                </block-definition>            </config>        </query-builder>    </QueryBuilderConfig></Configuration>

=== ahimanikya/FrescoMDM/solutions/aus-patient/AUSPatient/src/Configuration/query.xml
<?xml version="1.0" encoding="UTF-8"?><Configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema/query.xsd">    <QueryBuilderConfig module-name="QueryBuilder" parser-class="com.sun.mdm.index.configurator.impl.querybuilder.QueryBuilderConfiguration">        <query-builder name="ALPHA-SEARCH" class="com.sun.mdm.index.querybuilder.BasicQueryBuilder" parser-class="com.sun.mdm.index.configurator.impl.querybuilder.KeyValueConfiguration" standardize="false" phoneticize="false">            <config>                <option key="UseWildcard" value="true"/>            </config>        </query-builder>        <query-builder name="PHONETIC-SEARCH" class="com.sun.mdm.index.querybuilder.BasicQueryBuilder" parser-class="com.sun.mdm.index.configurator.impl.querybuilder.KeyValueConfiguration" standardize="true" phoneticize="true">            <config>                <option key="UseWildcard" value="false"/>            </config>        </query-builder>        <query-builder name="BLOCKER-SEARCH" class="com.sun.mdm.index.querybuilder.BlockerQueryBuilder" parser-class="com.sun.mdm.index.configurator.impl.blocker.BlockerConfig" standardize="true" phoneticize="true">            <config>                <block-definition  number="FirstNameLastNamePhon">                    <hint></hint>                    <block-rule>                        <equals>                            <field>Enterprise.SystemSBR.AUSPatient.FirstName_Phon</field>                            <source>AUSPatient.FirstName_Phon</source>                        </equals>                        <equals>                            <field>Enterprise.SystemSBR.AUSPatient.LastName_Phon</field>                            <source>AUSPatient.LastName_Phon</source>                        </equals>                    </block-rule>                </block-definition>                <block-definition  number="TFN">                    <hint></hint>                    <block-rule>                        <equals>                            <field>Enterprise.SystemSBR.AUSPatient.TFN</field>                            <source>AUSPatient.TFN</source>                        </equals>                    </block-rule>                </block-definition>                <block-definition  number="FirstNamePhoneDOBGender">                    <hint></hint>                    <block-rule>                        <equals>                            <field>Enterprise.SystemSBR.AUSPatient.FirstName_Phon</field>                            <source>AUSPatient.FirstName_Phon</source>                        </equals>                        <equals>                            <field>Enterprise.SystemSBR.AUSPatient.DOB</field>                            <source>AUSPatient.DOB</source>                        </equals>                        <equals>                            <field>Enterprise.SystemSBR.AUSPatient.Gender</field>                            <source>AUSPatient.Gender</source>                        </equals>                    </block-rule>                </block-definition>            </config>        </query-builder>    </QueryBuilderConfig></Configuration>
