=== ahimanikya/FrescoMDM/index-core/src/main/resources/filter/filter.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="filter">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="exclusion-List">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="field"  minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="name" type="xs:string" minOccurs="0" maxOccurs="1"  />
                                        <xs:element name="value"  minOccurs="1" maxOccurs="1" >
                                            <xs:complexType>
                                                <xs:choice>
                                                    <xs:element name="file"  minOccurs="1" maxOccurs="1" >
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="file-name" type="xs:string" minOccurs="0" maxOccurs="1"  />
                                                            </xs:sequence>
                                                            <xs:attribute name="delimiter" type="xs:string" use="required"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="field-value" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
                                                </xs:choice>   
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="sbr" type="xs:string" use="required"/>
                                    <xs:attribute name="matching" type="xs:string" use="required"/>
                                    <xs:attribute name="blocking" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="module-name" type="xs:string" use="required"/>
                        <xs:attribute name="parser-class" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ahimanikya/FrescoMDM/index-core/src/main/java/com/sun/mdm/index/filter/sample/filter.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<filter  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="filter.xsd">
    
    <exclusion-List  module-name="ExclusionFilter" 
                     parser-class="com.sun.mdm.index.filter.ExclusionFilterCofig" >
        
        <!-- Default list of value for all  sbr ,matching & blockings -->


        
        <field  sbr="true" matching="true" blocking="true" >
            <name>PatientView.FirstName</name>
            <value>
                <field-value>bill</field-value>
                <field-value>bills</field-value>
                <field-value>block</field-value>
                <field-value>match</field-value>
                <field-value>baby</field-value>
                <field-value>boby</field-value>
                <field-value>nirmal</field-value>
                <field-value>niru</field-value>
                <field-value>nishanth</field-value>
                <field-value>nisha</field-value>
                <field-value>deep</field-value>
                <field-value>sami</field-value>
            </value>
        </field>
        
        <field  sbr="true" matching="false" blocking="true" >
            <name>PatientView.LastName</name>
            <value>
                <file  delimiter=";">
                    <file-name>exclusionValues.txt</file-name> 
                </file>
            </value>
        </field>
        
        <field sbr="true" matching="true" blocking="false">
            <name>PatientView.SSN</name>
            <value>
                <file delimiter="|"> 
                    <file-name>matching.txt</file-name> 
                </file>
            </value>
        </field>  
        
        
        
        
        
    </exclusion-List>
</filter>

=== ahimanikya/FrescoMDM/index-core/src/main/resources/filter/filter.xml
<?xml version="1.0" encoding="UTF-8"?>
<filter  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="schema/filter.xsd">
    
    <exclusion-List  module-name="ExclusionFilter" 
                     parser-class="com.sun.mdm.index.filter.ExclusionFilterCofig">
        
        <!-- Default list of value for all  sbr ,matching & blockings -->
        <field  sbr="true" matching="true" blocking="true" >
            <!-- Field for exclusion -->
            <name></name>
            <value>
                <!-- Value to be excluded -->
                <field-value></field-value>
            </value>
        </field>

        <!-- Sample if using a file to define filter values -->
        <field sbr="true" matching="true" blocking="false">
            <!-- Field for exclusion -->
            <name></name>
            <value>
                <file delimiter="|"> 
                    <!-- File name containing list of excluded values -->
                    <file-name></file-name> 
                </file>
            </value>
        </field>
          
    </exclusion-List>
</filter>

=== ahimanikya/FrescoMDM/index-core/src/main/resources/filter/samplefilter.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<filter  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="filter.xsd">
    <exclusion-List module-name="ExclusionFilter" parser-class="com.stc.eindex.filter.ExclusionFilterCofig" >
        <field sbr="true" matching="false" blocking="false">
            <name>PatientView.FirstName</name>
            <value>
                <field-value>baby </field-value>
                <field-value>boby </field-value>
            </value>
        </field>
        <field sbr="true" matching="true" blocking="false">
            <name>PatientView.LastName</name>
            <value>
                <field-value> roy </field-value>
                <field-value>joy </field-value>
            </value>
        </field>
        <field sbr="false" matching="false" blocking="true">
            <name>PatientView.LastName</name>
            <value>
                <field-value>aaaa </field-value>
                <field-value> bbbb </field-value>
                </value>
        </field>
        <field sbr="true" matching="true" blocking="true">
            <name>PatientView.SSN</name>
            <value>
                <file delimiter="|"> 
                    <file-name> exclusionSSN.txt  </file-name> 
	        </file>
            </value>
        </field>
        <field sbr="false" matching="true" blocking="false">
            <name>PatientView.SSN</name>
            <value>
                <file delimiter="|"> 
                    <file-name>matching.txt </file-name> 
	        </file>
            </value>
        </field>  
        <field sbr="false" matching="true" blocking="true">
            <name>PatientView.Age</name>
            <value>
                <field-value> 999 </field-value>
                <field-value>000 </field-value>
                <field-value>777 </field-value>
            </value>
        </field> 
    </exclusion-List>
</filter>
