=== ahimanikya/FrescoMDM/solutions/usa-patient/USAPatient/src/Configuration/schema/security.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
	# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
	#
	# Copyright 2003-2007 Sun Microsystems, Inc. All Rights Reserved.
	#
	# The contents of this file are subject to the terms of the Common 
	# Development and Distribution License ("CDDL")(the "License"). You 
	# may not use this file except in compliance with the License.
	#
	# You can obtain a copy of the License at
	# https://open-dm-mi.dev.java.net/cddl.html
	# or open-dm-mi/bootstrap/legal/license.txt. See the License for the 
	# specific language governing permissions and limitations under the  
	# License.  
	#
	# When distributing the Covered Code, include this CDDL Header Notice 
	# in each file and include the License file at
	# open-dm-mi/bootstrap/legal/license.txt.
	# If applicable, add the following below this CDDL Header, with the 
	# fields enclosed by brackets [] replaced by your own identifying 
	# information: "Portions Copyrighted [year] [name of copyright owner]"
-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="Configuration">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="SecurityConfig" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="SecurityConfig">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="SecurityPlugInClass" />

				<xs:element name="ejbSecurity">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="ON" />
							<xs:enumeration value="OFF" />
						</xs:restriction>
					</xs:simpleType>

				</xs:element>
				<xs:element name="role" type="roleType" maxOccurs="unbounded"></xs:element>

			</xs:sequence>
			<xs:attribute name="module-name" type="xs:string" use="required" />
			<xs:attribute name="parser-class" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="SecurityPlugInClass" type="xs:string" />
	<xs:complexType name="operationsType">
		<xs:sequence>
			<xs:element name="name" type="xs:string" maxOccurs="unbounded"></xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="roleType">
		<xs:sequence>
			<xs:element name="role-name" type="xs:string"></xs:element>
			<xs:element name="operations" type="operationsType"></xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== ahimanikya/FrescoMDM/solutions/usa-citizen/USACitizen/src/Configuration/security.xml
<?xml version="1.0" encoding="UTF-8"?>
<Configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema/security.xsd">
    <SecurityConfig module-name="Security" parser-class="com.sun.mdm.index.configurator.impl.security.SecurityConfiguration">
        <SecurityPlugInClass></SecurityPlugInClass>
        <ejbSecurity>ON</ejbSecurity>
        <role>
            <role-name>MasterIndex.User</role-name>
            <operations>
                <name>lookupAssumedMatches</name>
                <name>lookupAuditLog</name>
                <name>lookupPotentialDuplicates</name>
                <name>lookupSystemDefinition</name>
                <name>lookupSystemDefinitions</name>
                <name>lookupSystemObjectPKs</name>
                <name>lookupSystemObjects</name>
                <name>lookupTransactions</name>
                <name>resolvePotentialDuplicate</name>
                <name>searchEnterpriseObject</name>
            </operations>
        </role>
    </SecurityConfig>
</Configuration>
